bool SwGrSetMode(uint16 mode) ;
void ini_SaveRBuf() ;
void DispSaveRBuf() ;
void printf_adc(uint8 new_adc) ;
void ini_progline() ;
void u100to1000(void) ;
void CvtENCR0(void) ;
void CvtENCR1(void) ;
bool chk_zrt_power_on(BYTE axis) ;
unsigned  		FindBIOSVendor() ;
unsigned  		FindSMBIOSTbl0();
void 			init_set3701cmd() ;
unsigned STATUS_ADDR(PHY_AXIS phy_axis) ;                    
unsigned STATUS_ADDR(uint8 phy_axis) ;                    
bool 			CHK_OVERFLOW(PHY_AXIS phy_axis) ;
bool 			CHK_OVERFLOW(uint8 phy_axis) ;
LOG_AXIS 		phy2logaxis(PHY_AXIS phy_axis);
LOG_AXIS 		phy2logaxis(uint8 card , uint8 localaxis);
uint8 			phy2localaxis(uint8 &card ,PHY_AXIS phy_axis);
uint8 			log2phyaxis(uint8 &card,LOG_AXIS laxis) ;
PHY_AXIS 		log2phyaxis(LOG_AXIS laxis) ;
Cptr 			SelStr(Cptr ch , Cptr en) ;
Cptr 			SelStr(bool force_eng, Cptr ch , Cptr en) ;
int16 			CursorStr(CursorData_t *ptr, Cptr buf,ProgType_t *pt) ;
void 			AB_manual_to_zero(bool &is_first_a) ;
void 			AcknowledgeInterrupt (short irq_number);
void  			ADD_Delay(ActTbl_t *a_tbl , uint16 &idx , int32 dw[] ,uint16 bDelay[]) ;
void  			ADD_Delay(ActTbl_t *a_tbl , uint16 &idx , uint16 bDelay) ;
void  			ADD_Delay(ActTbl_t *a_tbl , uint16 &idx ,uint8 seq[]  ,uint16 bDelay[]) ;
void  			ADD_Delay(ActTbl_t HUGE	*a_tbl , WORD &idx , SDWORD dw[] ,WORD bDelay[]) ;
void 			ADD_Delay(ActTbl_t HUGE	*a_tbl , WORD &idx , WORD bDelay) ;
void  			ADD_Delay(ActTbl_t HUGE	*a_tbl , WORD &idx ,BYTE seq[]  ,WORD bDelay[]) ;
void 			ADD_Delays(ActTbl_t 	*a_tbl , uint16 &idx , uint16 bDelay) ;
void  			ADD_Delays(ActTbl_t HUGE	*a_tbl , WORD &idx , WORD bDelay) ;
void 			ADD_INCY(ActTbl_t 	*a_tbl , uint16 &idx , uint16 line) ;
void 			ADD_INCY(ActTbl_t HUGE	*a_tbl , WORD &idx , WORD line) ;
void 			ADD_MDY_GAPY( ActTbl_t   *a_tbl, uint16 &idx , bool has_a) ;
void 			ADD_MDY_GAPY( ActTbl_t HUGE  *a_tbl, WORD &idx , bool has_a) ;
void 			ADD_Modify_y(ActTbl_t *a_tbl , uint16 &idx,bool has_a) ;
void 			ADD_Modify_y(ActTbl_t HUGE	*a_tbl , WORD &idx,bool has_a) ;
void 			ADD_OFFSET_Y(ActTbl_t 	*a_tbl , uint16 &idx) ;
void 			ADD_OFFSET_Y(ActTbl_t HUGE	*a_tbl , WORD &idx) ;
void 			ADD_SAVE_Y_MOV( ActTbl_t   *a_tbl, uint16 &idx, int32 ymov) ;
void 			ADD_SAVE_Y_MOV( ActTbl_t HUGE  *a_tbl, WORD &idx, SDWORD ymov) ;
void 			ADD_WaitMotorNear(ActTbl_t 	*a_tbl , uint16 &idx , uint8 axis) ;
void 			ADD_WaitMotorNear(ActTbl_t HUGE	*a_tbl , WORD &idx , BYTE axis) ;
void 			Adjust_AZero(void);
void 			Adjust_DWORD(uint32 *td);
void 			Adjust_ProgBuf(ProgType_t *data,uint16 num);
void 			Adjust_WORD(uint16 *td);
void 			AGAPMody (void) ;
void 			AHomeMody (void);
void 			AirMody (void);
bool 			allAtHome();
void 			always_run() ;
void  			always_run() ;
void  			d() ;
void 			always_update() ;
void 			ascii_out_q(SCRN_XY x , SCRN_XY y , COLOR_T color , Cptr buf ,bool reverse );
void 			ascii_out_proc(void *ptr);
void 			AtHome(BYTE axis) ;
void 			AtHome(uint8 axis) ;
void 			AUTO_FIELD(ProgType_t  *prog , uint8 digit,uint8 axis) ;
void 			AUTO_FIELD(ProgType_t huge *prog , BYTE digit,BYTE axis) ;
void 			AUTO_FIELD_SAME(ProgType_t  *prog , uint8 digit,uint8 axis) ;
void 			AUTO_FIELD_SAME(ProgType_t huge *prog , BYTE digit,BYTE axis) ;
void 			AUTO_FIELD_Y(ProgType_t *prog , uint8 digit,uint8 axis)	;
void 			AUTO_FIELD_Y(ProgType_t huge *prog , BYTE digit,BYTE axis)	;
void 			AUTO_RUN() ;
bool 			AutoHook_in_axis_d(uint16 line,uint16 startx , uint16 endx) ;
bool 			AutoHook_in_axis_d(WORD line,WORD startx , WORD endx) ;
void 			AutoTest() ;
void 			AXISA_to_home() ;
void 			AxisDelayMody (void) ;
void 			AxisStartDegree (BYTE gn);
void 			AxisStartDegree (uint8 gn);
void 			backup(void) ;
void 			bar256(SCRN_XY x1,SCRN_XY y1,SCRN_XY x2,SCRN_XY y2 , COLOR_T c);
void 			bar256(SCRN_XY y1,SCRN_XY y2 , COLOR_T c);
void 			bar256_00(void *dptr);
void 			bar256_proc(void *dptr);
void 			bar256_q(SCRN_XY x1,SCRN_XY y1,SCRN_XY x2 , SCRN_XY y2 , COLOR_T color) ;
void 			bar256_queue(SCRN_XY x1,SCRN_XY y1 , SCRN_XY x2,SCRN_XY y2 , COLOR_T c);
void 			BATCHMody (void);
void 			BATCHnMody (void);
uint16 			BcdToBin (short nibble, uint16 w);
uint32 			BcdToBin (short nibble, uint32 w);		//盢BCD絪絏(w),计(nibble)锣传Θbinary code 肚
int32 			BcdToBin (short nibble, uint32 w,uint8 s);
uint8 			BcdToBin (short nibble, uint8 w);
uint32 			BcdToBin_X (uint32 w);
uint8 			BcdToStrBuf (uint8 digit, uint32 val, Cptr buf);// 盢val锣传Θdigitせ秈计,buf┮计⊿Τ干NULL 肚:digit
uint8 			BcdToStrBuf (uint8 digit, uint32 val, ept_char buf);
uint8 			BcdToStrBuf (uint8 digit, uint32 val, Cptr buf,uint8 *sign,int dotpos) ;
void 			big30(SCRN_XY x , SCRN_XY y , COLOR_T color , Cptr buf ,bool reverse,int8 pointpos);
void 			big48(SCRN_XY x , SCRN_XY y , COLOR_T color , Cptr buf ,bool reverse,int8 pointpos);
void 			big_smallnum(SCRN_XY x , SCRN_XY y , COLOR_T color , Cptr buf ,bool reverse, int size,int8 pointpos );
int  			big_smallnumc(SCRN_XY x , SCRN_XY y , COLOR_T color , unsigned char t ,bool reverse, int size );
void 			bignum(SCRN_XY x , SCRN_XY y , COLOR_T color , Cptr buf ,bool reverse,int8 pointpos );
uint8 			BinToStrBuf (uint8 digit, uint32 val, Cptr buf);// 盢val锣传Θdigit秈计,buf┮计⊿Τ干NULL 肚:digit
uint8 			BinToStrBuf (uint8 digit, uint32 val, ept_char buf);
void 			BoolMody (void);
void 			BUZZERMody (void);
void 			cal_dw_X(int32 dw[] , int32	lpos[],int32 e , int32 s,uint16 line) ;
void 			cal_dw_X(SDWORD dw[] , SDWORD	lpos[],SDWORD e , SDWORD s,WORD line) ;
void 			cal_dw_X(ept_SDWORD dw , ept_SDWORD lpos,	SDWORD sde , SDWORD s,WORD line) ;
void 			cal_dw_Y(ProgType_t *p_buf,int32 &dw	, int32 lpos[]) ;
void 			cal_dw_Y(ProgType_t HUGE  *p_buf,SDWORD &dw	, SDWORD lpos[]) ;
void 			cal_dw_ZABC(ProgType_t	 *p_buf,int32 dw[] , int32	lpos[]) ;
void 			cal_dw_ZABC(ProgType_t	 *p_buf,uint8 axis , int32 &dw , int32	lpos[],int32 tlpos[]) ;
void 			cal_dw_ZABC(ProgType_t	*p_buf,uint8 axis , int32 &dw , int32	lpos[]) ;
void 			cal_dw_ZABC(ProgType_t	HUGE *p_buf,BYTE axis , SDWORD &dw , SDWORD	lpos[],SDWORD tlpos[]) ;
void 			cal_dw_ZABC(ProgType_t	HUGE *p_buf,BYTE axis , SDWORD &dw , ept_SDWORD	lpos,SDWORD tlpos[]);
void 			cal_dw_ZABC(ProgType_t	HUGE *p_buf,BYTE axis , SDWORD &dw , SDWORD	lpos[]) ;
void 			cal_dw_ZABC(ProgType_t	HUGE *p_buf,BYTE axis , SDWORD &dw , ept_SDWORD	lpos) ;
void			cal_dw_ZABC(ProgType_t HUGE *p_buf,BYTE axis , SDWORD &dw , ept_SDWORD lpos);
void 			cal_dw_ZABC(ProgType_t	HUGE *p_buf,SDWORD dw[] , SDWORD	lpos[]) ;
void 			cal_dw_ZABC(ProgType_t	HUGE *p_buf,ept_SDWORD dw , ept_SDWORD	lpos) ;
void 			Cal_Grid_1ms(uint16 speed);
void 			Cal_Grid_1ms(WORD speed);
unsigned int 	cal_intvect(int no) ;
void 			cal_pass(void) ;
void 			cal_ref(DWORD ref[]) ;
void 			cal_ref(DWORD ref[],WORD speed) ;
void 			cal_ref(ept_DWORD ref) ;
void 			cal_ref(ept_DWORD ref,WORD speed) ;
void 			cal_ref(uint32 ref[]) ;
void 			cal_ref(uint32 ref[],uint16 Rate[]) ;
void 			cal_ref(uint32 ref[],uint16 speed) ;
void 			cal_rrpm(unsigned long t1,unsigned long &ticks,int &rpm , int &rpmd) ;
bool 			cal_YYYYMMDD(uint32 &YYYYMMDD);
void 			cal_zrtref(BYTE axis,DWORD &ref) ;
void 			cal_zrtref(uint8 axis,uint32 &ref) ;
DWORD 			cal_ZrtSpeed(BYTE axis , short speed_factor) ;
bool 			check_manval0(uint8 axis) ;
void 			CHECK_RESET(bool stopmotor) ;
void 			CHECK_RESET_update(bool stopmotor) ;
bool 			check_setting() ;
void 			CheckCCYMark (void);
void 			CheckESCChar (Cptr p);
char 			CheckOverUsedTimes (void);
void 			chg_newspeed(bool speedup);
void 			ChgCursorID (uint16 new_cursorID);
void			ChgCursorLoc (WORD new_cursor_loc);
void 			ChgSpeed(int inc) ;
void 			ChgToModyMode (uint16 op_mode);
void 			ChgToModyMode (WORD op_mode);
void 			ChgToMovMode (uint16 op_mode);
void 			ChgToMovMode (WORD op_mode);
bool 			Chk3701 (uint8 axis);
bool 			Chk3701 (PHY_AXIS phy_axis);
int 			Chk3701No (void);
bool 			CHK_ARM_CMD(uint8 cmd) ;
bool 			CHK_PC_CMD(uint8 cmd) ;
bool 			chk_AXIS_Y(uint8 axis) ;
bool 			chk_ccyfile();
bool 			chk_changepoint(uint16 no,uint16 lpos) ;
bool 			chk_changepoint(WORD no,WORD lpos) ;
int  			chk_cts();
int 			chk_cts();
void 			Chk_e_air(ActTbl_t   *a_tbl , uint16	&idx,uint8 &e_air,int32	 s,uint8 n_air) ;
void 			Chk_e_air(ActTbl_t  HUGE *a_tbl , WORD	&idx,BYTE &e_air,SDWORD	 s,BYTE n_air) ;
void			Chk_Loop_e_air(ActTbl_t  HUGE *a_tbl , WORD	&idx,BYTE &e_air,SDWORD	 s , BYTE n_air);
void 			chk_ErrMsg() ;
bool 			chk_free_proc_queue();
bool 			chk_Graphfile() ;
bool 			CHK_KEY() ;
void 			chk_limit() ;
void 			chk_off_power(BYTE loc) ;
void 			chk_off_power(uint8 loc) ;
bool 			chk_over_home(BYTE axis) ;
bool 			chk_over_home(BYTE axis) ; 
bool 			chk_over_home(uint8 axis) ;
bool 			CHK_OVERFLOW(BYTE axis);
bool 			CHK_OVERFLOW(uint8 axis);
bool 			chk_PROG_VAL_NULL(int axis, int line) ;
int  			chk_rs232();
int 			chk_rs232();
void 			CHK_RW3701Err(bool cond , PHY_AXIS phy_axis , char *mes , DOS_ADDR addr , int val , DWORD loops) ;
void 			CHK_RW3701Err(bool cond , uint8 axis , char *mes , unsigned addr , int val , uint32 loops) ;
void 			chk_ScrnSav() ;
uint8 			chk_ST51_DATAOK1(uint8 ret) ;
uint8 			chk_ST51_NEAR_OK(uint8 ret) ;
uint8 			chk_ST51_NEAR_OK_RESEND_OVERLAY(uint8 ret) ;
bool 			chk_utouch(uint16 no,uint16 start , uint16 end) ;
bool 			chk_utouch(WORD no,WORD start , WORD end) ;
bool 			chk_valid_num(char *buf);
bool 			chk_zval_no0() ;
short			ChkAllMotorFinish (void);
short 			ChkAllMotorFinish (void);
void			ChkAxisVal (BYTE axis, BYTE *sign, int *val);
void			ChkAxisVal (BYTE axis, BYTE *sign, DWORD *val);
void 			ChkAxisVal (uint8 axis, uint8 *sign, uint32 *val);
void 			DispCurAxis_q (short force);
void			DispCurLine();
short 			ChkCmdZrt (BYTE axis);
short 			ChkCmdZrt (uint8 axis);
void 			ChkDoorStop (void);
void 			ChkExStop (void);
void 			ChkExtRstSW(void) ;
short 			ChkExtRstSW_IO (void);
short			ChkExtRstSW_IO (void);
CursorData_t** 	ChkField (CursorData_t **ptr, uint16 no);
CursorData_t** 	ChkField (CursorData_t **ptr, WORD no);
void 			ChkG2G1() ;
void 			ChkManMov() ;
void 			ChkOilStop (void);
void 			ChkOverFlowStop (void);
bool 			chkOverLimit(uint8 axis,uint8 dir,uint8 man_hand);
void 			chkRUNDAYS_Over(void) ;
short 			ChkSafePlugIn (void);
void 			ChkSaveAir (void);
void 			ChkSaveVal (void);
void 			ChkStartWire (int32 mov);
void 			ChkStopWire (void);
void 			chksum_err(void) ;
void 			CIR_TO_GRID(BYTE axis,SDWORD &tt) ;
void 			CIR_TO_GRID(uint8 axis,int32 &tt) ;
void 			ClearCCYMark (void);
void 			ClearMessageWin (void);
void  			ClearStringArea (short lx, short ly, short char_no, COLOR_T color);
void 			ClearStringArea (short lx, short ly, short char_no, short color);
void 			ClearTimer (short idx);
void 			close_config(void);
void 			close_dump_proc_queue(void);
void 			close_intTouch_Home(void);
void 			close_record(void);
void 			closevideo(void );
void 			Clr2016s(short axis) ;
uint8 			Clr68KInterrupt (void);
BYTE 			Clr68KInterrupt (void);
void 			CLR_MSG_WIN_proc(void *dptr);
void 			CLR_RUN_WIN_proc(void *dptr);
void 			Clr_Set3701_ARM() ;
void 			CLR_TOUCH_proc(ProgType_t  *p_buf,ActTbl_t  *a_tbl, uint16 &idx) ;
void 			CLR_TOUCH_proc(ProgType_t HUGE *p_buf,ActTbl_t HUGE *a_tbl, WORD &idx) ; 
void 			clr_zrt_power_on(BYTE axis) ;
void 			ClrIndexWindow(void) ;
void 			ClrIndexWindow_q(void) ;
uint8 			ClrKeyBuf (void);
BYTE 			ClrKeyBuf_leave1code (void);
void 			ClrMsgWin (void);
void 			ClrMsgWin_proc(void *dptr);
void 			ClrMsgWin_q (void);
void 			ClrRunMessageWin (void);
void 			ClrRunWin_q (void);
void 			ClrStatusBar_q (void);
void 			ClrTouchPos (short mode, uint16 flag);
void 			ClrTouchPos (short mode, WORD flag);
void 			cnt8254Mody(void);
short 			ColorStringLen (char *str);
void 			com_FileMody() ;
void 			CommentMody (void) ;
void 			complete_spring() ;
void 			complete_spring_cmd() ;
void			DispTestMsg_q();
void 			Convg0ToSpace(int g0line,int fileno) ;
short 			CopyDiskFile (uint16 file_no, uint16 file_name);
void 			CRT_OFF() ;
void 			CRT_ON() ;
void 			CurQuanMody(void);
void 			CursorOrg(bool flag)  ;
void 			CursorStr(CursorData_t *ptr, Cptr buf) ;
int32 			cvt_100(int32 mov);
SDWORD 			cvt_100(SDWORD mov);
void 			d_acc_no_curve_bg(void *dptr);
void 			d_acc_no_curve_bg_00(void *dptr);
void 			d_curve_bg_lenchk(void *dptr);
void 			d_curve_bg_lenchk_01(void *dptr);
void 			d_lenchk_screen(void *dptr);
void 			d_lenchk_screen_01(void *dptr);
void 			d_lenchk_screen_01a(void *dptr);
void 			d_lenchk_screen_01b(void *dptr);
void 			d_lenchk_screen_01c(void *dptr);
void 			d_lenchk_screen_02(void *dptr);
void 			d_lenchk_screen_02a(void *dptr);
void 			d_lenchk_screen_03(void *dptr);
void 			d_lenchk_screen_04(void *dptr);
void 			d_lenchk_screen_05(void *dptr);
DWORD 			dBinToBcd (short nibble, DWORD w);
uint32 			dBinToBcd (short nibble, int32 w,uint8 &sign) ;
DWORD 			dBinToBcd (short nibble, SDWORD w,BYTE &sign) ;
uint32 			dBinToBcd (short nibble, uint32 w);
DWORD 			dBinToBcd_X ( DWORD w);
uint32 			dBinToBcd_X ( uint32 w);
int 			dBMOTORUNIT_X() ;
void 			Dec_dw(ProgType_t   *p_buf,int32 &dw);
void 			Dec_dw(ProgType_t HUGE  *p_buf,SDWORD &dw);
void 			DecDistMody (void);
void 			DefaultButtonStyle (Frame_t *frame);
void 			DEG_TO_GRID(BYTE axis, SDWORD &tt) ;
void 			DEG_TO_GRID(uint8 axis, int32 &tt) ;
void 			DelActiveProgLine (void);
void 			Delay0d1s (uint16 cnt);
void 			Delay0d1s (WORD cnt);
void 			DelayCount (DWORD cnt);
void 			DelayCount (uint32 cnt);
void 			DelayCount_pc (unsigned long count);
void 			DelayMody (void);
void 			DelayTick (unsigned ticks);
void 			DelCurAirLine (void);
void 			DelCurProgLine (void);
void 			disable_all_touch();
void			DisableHomeInt();
void 			DisableHomeInt (uint8 axis);
void 			DisableHomeInt (uint8 axis,uint8 mask );
void 			DisableHomeInt67 (BYTE axis);
void 			DisableHomeInt67 (uint8 axis);
void 			DisableInterrupt (short irq_number);
void 			DISP_BIG_DIGIT_proc(void *dptr);
void 			DISP_CUR_PROGLINE(int x, int y, int disp_line, BYTE mode);							
void 			DISP_CUR_PROGLINE(int x, int y, int disp_line, uint8 mode);							
void 			DISP_CUR_PROGLINE_Q(int x,int  y,int  disp_line,BYTE  mode) ;
void 			DISP_CUR_PROGLINE_Q(int x,int  y,int  disp_line,uint8  mode) ;
void 			DISP_EDIT_PROGLINE(int x, int y, int disp_line, BYTE mode);	
void 			DISP_EDIT_PROGLINE(int x, int y, int disp_line, uint8 mode);	
void 			DISP_EDIT_WINDOW_proc(void *dptr);
void 			DISP_HELP_WINDOW_proc(void *dptr);
void 			DISP_ICON_proc(void *dptr);
void 			DISP_LED_proc(void *dptr);
void 			DISP_MODY_WINDOW_proc(void *dptr);
void 			DISP_MSG_WIN_proc(void *dptr);
void 			DISP_PARA_NOPASS_WINDOW_proc(void *ptr) ;
void 			DISP_PARA_WINDOW_proc(void *dptr);
void 			DISP_PROG_proc(void *dptr);
void 			DISP_RUN_MSG_proc(void *dptr);
void 			DISP_RUN_WIN_proc(void *dptr);
void 			DISP_SAFE_proc(void *dptr);
void 			DISP_STEP_WINDOW_proc(void *dptr);
void 			DISP_STR2_proc(void *dptr);
void 			DISP_STR_proc(void *dptr);
void 			DISP_TEST_WINDOW_proc(void *dptr);
void 			Disp_USB_WARN() ;
void 			DISP_WORK_WINDOW_proc(void *dptr);
void 			DispAbsPos();
void 			DispActAir (short set);
void 			DispAirBox_q (void);
void 			DispAirLine (uint16 x, uint16 y, uint16 disp_line, ProgType_t *prog, uint16 mode);
void 			DispAirLine (WORD x, WORD y, WORD disp_line, ProgType_t huge *prog, WORD mode);
void 			DispAirLine_q (uint16 x, uint16 y, uint16 disp_line, ProgType_t *prog, uint16 mode);
void 			DispAirLine_q (WORD x, WORD y, WORD disp_line, ProgType_t huge *prog, WORD mode);
void 			DispAirTitle_q (void) ;
void 			DispAirWindow(void) ;
void 			DispAxisFrame_q (void);
void 			DispAxisName_q (void);
void 			DispAxisPosManHandFrame (short idx);
void 			DispBUZZER_proc(void *ptr) ;
void 			DispBUZZER_q(BYTE idx);
void 			DispBUZZER_q(uint8 idx);
void 			DispComment_q() ;
void 			DispCurAxis (short force);
void 			DispCurAxis_q (short force);
void 			DispCurPassword_q (void);
void 			DispCurPosDelay (void);
void 			DispCurPosDelay_q (void);
void 			DispCurProgList (short line);
void 			DispCurProgList_q (short line);
void 			DispDoorError();
void 			DispEditBox (void);
void 			DispEditBox_q (void);
void 			DispEditTitle_q (void);
void 			DispEditWin_q (short all);
void 			DispEditWin_q (short disp_all);
void 			DispErr(bool disp, bool save) ;
void 			DispExError_q();
void 			DispExtEncoderError() ;
void 			DispFile_q (void);
void 			DispFileFrame1_proc (void *dptr);
void 			DispFileFrame2_proc (void *dptr);
void 			DispFileFrame_q (void);
void 			DispFileFrameIndex1_proc (void *dptr) ;
void 			DispFileFrameIndex2_proc (void *dptr) ;
void 			DispFileRWError (short wr);
void 			DispFileRWError_q (short wr);
void 			DispGoHomeFailure(int8 axis) ;
void 			DispGraphic_q() ;
void 			DispHandFrame1_proc(void *dptr);
void 			DispHandFrame2_proc(void *dptr);
void 			DispHandFrame_q (void);
void 			DispHandVal_q (void);
void 			DispHelpBox (void);
void 			DispHelpContent (void);
void 			DispHelpWin_ncrt_q (short all);
void 			DispHelpWin_q (short all);
void 			DispHelpWin_q (short disp_all);
void 			DispIcon_proc(void *dptr);
void 			DispIcon_q (SCRN_XY lx, SCRN_XY ly, uint16 idx, uint16 op_mode);
void 			DispIndex_q() ;
void 			DispIndex_q(uint16 idx,bool flash_mode) ;
void 			DispIndex_q(WORD idx,bool flash_mode) ;
void 			DispIndex_window_q() ;
void 			DispIndexBox_q (void) ;
void 			DispIndexContent_proc(void *ptr) ;
void 			DispIndexContent_q() ;
void 			DispIndexContent_q(bool flash) ;
void 			DispInport(void) ;
void 			DispKeyscrn_proc(void *ptr);
void 			DispKeyscrn_q(BYTE idx) ;
void 			DispKeyscrn_q(uint8 idx) ;
void 			DispLimError (int no) ;
void 			DispMainMode_q(short idx) ;
void 			DispMainWindow_q () ;
void 			DispMainWindow_q (short idx, short only_title);
void 			DispManFrame_q (void);
void 			DispManualSet_q(void) ;
void 			DispManVal_q (void);
void 			DispMessageWin (short lx, short ly, BYTE type, char *str);
void 			DispMessageWin (short lx, short ly, uint8 type, char *str);
void 			DispMissFrame1_proc (void *dptr);
void 			DispMissFrame2_proc (void *dptr);
void 			DispMissFrame_q (void);
void 			DispMissNo_q (void);
void 			DispModeFrame_proc (void* dptr);
void 			DispModeFrame_q (void);
void 			DispModyWin_q (short all);
void 			DispModyWin_q (short disp_all);
void 			DispMotorUnconnectError (short axis) ;
void 			DispMovAxis_q (BYTE axis);
void 			DispMovAxis_q (uint8 axis);
void 			DispMsgWin (short lx, short ly, BYTE type, Cptr str);
void 			DispMsgWin_proc(void *dptr);
void 			DispMsgWin_q(SCRN_XY x, SCRN_XY y, uint8	type, Cptr msg_chinese, Cptr msg_english) ;
void 			DispMsgWin_q(SCRN_XY x, SCRN_XY y, uint8 type, Cptr msg);
void 			DispMsgWin_q(SCRN_XY x, SCRN_XY y, BYTE	type, Cptr msg_chinese, Cptr msg_english, Cptr msg_Italian) ;
void 			DispOilError_q() ;
void 			DispOverUsed (void);
void 			DispPageAir (uint16 cur_line);
void 			DispPageAir (WORD cur_line);
void 			DispPageProg_proc (void *ptr) ;
void 			DispPageProg_q (uint16 cur_line);
void 			DispPageProg_q (WORD cur_line);
void 			DispPara10_nopass_q (void) ;
void 			DispPara_q(void);
void        DispPara_q(int no) ;
void 			DispParaAProg_q (void);
void 			DispParaAProgFrame1_proc (void *dptr);
void 			DispParaAProgFrame_q (void);
void 			DispParaBox_q (void);
void 			DispParacurField_q (short table_no) ;
void 			DispParaExt10_q (void);
void 			DispParaExt10Frame_proc (void *dptr);
void 			DispParaExt10Frame_q (void);
void 			DispParaExt9_q (void);
void 			DispParaExt9Frame_proc (void *dptr);
void 			DispParaExt9Frame_q (void);
void 			DispParaExt_q (void);
void 			DispParaExtFrame_proc (void * dptr);
void 			DispParaExtFrame_q (void);
void 			DispParaField_nopass_q(void) ;
void 			DispParaField_q(short table_no) ;
void 			DispParaField_q(void) ;
void 			DispParaFProg_q (void);
void 			DispParaFProgFrame1_proc (void *dptr);
void 			DispParaFProgFrame_q (void);
void 			DispParaFrame_com(short x , short y , char *ParaStr) ;
void 			DispParaFrame_proc (void *ptr) ;
void 			DispParaFrame_q (short table_no) ;
void 			DispParaLang_q (void);
void 			DispParaMotorFrame1_proc (void *dptr);
void 			DispParaMotorFrame2_proc (void *dptr);
void 			DispParaMotorFrame_q (void);
void 			DispParaMotorGrid_nopass_q (void) ;
void 			DispParaMotorGrid_q (void);
void 			DispParaNEAR_nopass_q (void) ;
void 			DispParaSPIN_ZRT_nopass_q (void) ;
void            DispParaWILE_MODE_nopass_q (void);
void 			DispParaSumFrame_proc (void* dptr);
void 			DispParaSumFrame_q (void);
void 			DispParaSumSpd_q (void);
void 			DispParaSysFrame_proc (void* dptr);
void 			DispParaSysFrame_q (void);
void 			DispParaUnit_q(void) ;
void 			DispParaWin_ncrt_nopass_q (short all) ;
void 			DispParaWin_ncrt_q (short all);
void 			DispParaWin_nopass_q (short disp_all) ;
void 			DispParaWin_q (short all);
void 			DispParaWin_q (short disp_all);
void 			DispParaY0_nopass_q (void) ;
void 			DispParaZrtMode_q(void) ;
void 			DispPass_q(void);
void 			DispPassWin_q (short all) ;
void 			DispPasswordFrame_proc(void *dptr);
void 			DispPasswordFrame_q (void);
void 			DispPosFrame_q (void);
void 			DispPrinterError (void);
void 			DispPrinterFile (void) ;
void 			DispPrinterOK (void);
void 			DispProg (short s_idx, short m_idx, short h);
//void 			DispProgLine (uint16 x, uint16 y, uint16 disp_line, ProgType_t *prog, uint16 mode);
//void 			DispProgLine (WORD x, WORD y, WORD disp_line, ProgType_t huge *prog, WORD mode);
void 			DispProgLine_proc (void *ptr) ;
//void 			DispProgLine_q(uint16 x, uint16 y, uint16 disp_line, ProgType_t *prog, uint16 mode);
//void 			DispProgLine_q(WORD x, WORD y, WORD disp_line, ProgType_t huge *prog, WORD mode);
void 			DispProgLine_test (short y, short disp_line, bool mode) ;
void 			DispProgList (short start_idx, short y_off, short lines);
void 			DispProgList_proc(void *dptr);
void 			DispProgList_q (short start_idx, short y_off, short lines);
void 			DispQuanFrame1_proc (void * dptr);
void 			DispQuanFrame1_proc (void *dptr);
void 			DispQuanFrame2_proc (void *dptr);
void 			DispQuanFrame_q (void);
void 			DispQuanNo_q (char which);
void 			DispRollData1_proc (void *dptr);
void 			DispRollData_proc(void * dptr);
void 			DispRollData_q (short x, short y, short step);
void 			DispRunMessage ();
//void 			DispRunMessage (unsigned long curquan, unsigned long setquan);
void sendhand(uint8 axis,uint8 meg);
void 			DispRunMessageWin (void);
void 			DispRunMsg_q (DWORD cur_quan, DWORD set_quan);
void 			DispRunMsg_q (uint32 cur_quan, uint32 set_quan);
void 			DispRunWin_q (void);
void 			DispRW3701Error (BYTE type , WORD mask);
void 			DispRW3701Error (uint8 type , uint16 mask);
void 			DispSafeSw(short mode);
void 			DispSafeSw1_proc(void *dptr);
void 			DispSafeSw_proc(void *dptr);
void 			DispSafeSw_q (short mode);
void 			DispSafeSwitch (short mode);
void 			DispSafeSwitch1_proc(void *dptr);
void 			DispServoFailure(int8 axis) ;
void 			DispSlideError () ;
void			DispServoCutterError() ;
void 			DispSN(BYTE mode) ;
void 			DispSN(uint8 mode) ;
void 			DispSpeed1_q(void) ;
void 			DispSpeed_q (void);
void 			DispSpeedFrame1_proc (void *dptr);
void 			DispSpeedFrame2_proc (void *dptr);
void 			DispSpeedFrame_q (void);
void 			DispStatusBar_q (Cptr str);
void 			DispStatusBar_q (Cptr str,COLOR_T fcol) ;
void 			DispStatusBar_q (int off, Cptr str) ;
void 			DispStatusBar_q (int off, Cptr str,COLOR_T fcol);
void 			DispStepWin_q (short all);
void 			DispStepWin_q (short disp_all);
void 			DispStrLine2_q (SCRN_XY lx, SCRN_XY ly, COLOR_T fcol, COLOR_T bcol, Cptr str,Cptr stro);
void 			sDispStrLine2_q (SCRN_XY lx, SCRN_XY ly, COLOR_T fcol, COLOR_T bcol, Cptr str,Cptr stro);
void 			DispStrLine_q (SCRN_XY lx, SCRN_XY ly, COLOR_T fcol, COLOR_T bcol, Cptr str);
void 			sDispStrLine_q (SCRN_XY lx, SCRN_XY ly, COLOR_T fcol, COLOR_T bcol, Cptr str);
void 			DispTestMsg_proc() ;
void 			DispTestWin_q (short all);
void 			DispTestWin_q (short disp_all);
void 			DispToolBar1_proc(void *dptr);
void 			DispToolBar_q (short idx);
void 			DispTouchFrame1_proc (void * dptr);
void 			DispTouchFrame_q (void);
void 			DispTouchPos (void);
void 			DispRPM (int RPM);
void 			CloseRPM ();
void 			DispTouchTitle(uint16 & ly,uint16 flag) ;
void 			DispWorkWin_q (short all);
void 			DispWorkWin_q (short disp_all);
void 			DisUSB(void) ;
int 			dMOTORUNIT_X() ;
void 			DrawButton (short x1, short y1, short x2, short y2, Frame_t *frame);
void 			DrawButton1234_proc(void *dptr);
void 			DrawButton12_proc(void *dptr);
void 			DrawButton1_proc(void *dptr);
void 			DrawButton2_proc(void *dptr);
void 			DrawButton34_proc(void *dptr);
void 			DrawButton3_proc(void *dptr);
void 			DrawButton4_proc(void *dptr);
void 			DrawButton_col1(short x1,short y1 , short x2,short y2,COLOR_T col1);
void 			DrawButton_col1(short x1,short y1 , short x2,short y2,short col1);
void 			DrawButton_col2(short x1,short y1 , short x2,short y2,COLOR_T col2);
void 			DrawButton_col2(short x1,short y1 , short x2,short y2,short col2);
void 			DrawButton_col3(short x1,short y1 , short x2,short y2,short col3);
void 			DrawButton_col3(short x1,short y1 , short x2,short y2,COLOR_T col3);
void 			DrawButton_col4(short x1,short y1 , short x2,short y2,short col4);
void 			DrawButton_col4(short x1,short y1 , short x2,short y2,COLOR_T col4);
void 			DrawButton_q (short x1, short y1, short x2, short y2, Frame_t *frame);
void 			DrawCasing (short x1, short y1, short x2, short y2, Frame_t *frame);
void 			DrawCasing_q (short x1, short y1, short x2, short y2, Frame_t *frame);
void 			DrawCasingLine (short x1, short y1, short x2, short y2, Frame_t *frame);
void 			DrawHLightBar (short lx, short ly, short rx, short ry, short percent);
void 			DrawScrollHBar (short lx, short ly, short rx, short ry, short percent);
void 			DrawScrollVBar (short lx, short ly, short rx, short ry, short percent);
void 			DrawScrollVBar_q (short lx, short ly, short rx, short ry, short percent);
void 			DrawTextButton (WinStyle_t *style);
void 			DrawTextButton1_proc(void *dptr);
void 			DrawWindow (WinStyle_t *style);
void 			DrawWindow_q (WinStyle_t *style);
void 			DrawWindowTitle (WinStyle_t *style);
void 			DrawWindowTitle_q (WinStyle_t *style);
uint32 			dReadAbsPos (uint8 axis);
DWORD 			dReadAbsPos (PHY_AXIS phy_axis) ;
void 			dump_proc_queue(void);
void 			DumpActTbl(int e);
//void 			DumpAirFile(FILE *fp);
void 			DumpAirTbl(int e);
//void 			DumpFile(FILE *fp);
void 			DumpFloppy(int name);
void 			dw_rs232();
SDWORD 			DWBcdAddBin (BYTE *sign, DWORD *bcdval, SDWORD binval);
int32 			DWBcdAddBin (uint8 *sign, uint32 *bcdval, int32 binval);
void 			EmStop (BYTE axis);
void 			EmStop (uint8 axis);
void 			enable_all_touch();
void            EnableHomeInt(uint8 axis, uint8 mask , uint8 type) ;
void 			EnableHomeInt (uint8 axis,uint8 type);
void 			EnableHomeInt (uint8 axis);
void 			EnableHomeInt67 (uint8 axis);
void 			EnableInterrupt (short irq_number);
void 			EnUSB(void) ;
bool 			exe_proc_queue(void);
void 			exit_Oil() ;
int32 			ExtGrid2_Grid(int32 mov) ;
SDWORD 			ExtGrid2_Grid(SDWORD mov) ;
char 			far * MakeFarPointer (char far *p);
void 			FAST_FIELD(ProgType_t *prog , uint8 digit,uint8 axis) ;
void 			FAST_FIELD(ProgType_t huge *prog , BYTE digit,BYTE axis) ;
void 			FAST_FIELD_SAME(ProgType_t *prog , uint8 digit,uint8 axis) ;
void 			FAST_FIELD_SAME(ProgType_t huge *prog , BYTE digit,BYTE axis) ;
void 			FAST_FIELD_Y(ProgType_t  *prog , uint8 digit,uint8 axis)  ;
void 			FAST_FIELD_Y(ProgType_t huge *prog , BYTE digit,BYTE axis)  ;
void 			FAST_RUN() ;
void 			FASTMody (void);
void 			FEEDERMody (void) ;
bool 			FileExisted(char *filename) ;
void 			FileMody (void);
long 			filesize(char *filename) ;
//long 			filesize(FILE *stream) ;
//long 			filesize(FILE *stream);
long 			filesize_config() ;
unsigned char*	filetobuf(char *filename);
void 			FILL_AIRTBL(ProgType_t	*p_buf,uint16 &idx) ;
void 			FILL_AIRTBL(ProgType_t	huge *p_buf,WORD &idx) ;
void 			fill_AutoHook_axis() ;
void 			fill_AutoHook_startx_endx() ;
void 			fill_key_buf(int code);
bool 			FILL_PC_CMD(uint8 cmd) ;
bool 			FILL_PC_CMD(BYTE cmd,bool *CardStatus) ;
bool 			FILL_PC_CMD_CHK_ARM_CMD(uint8 cmd) ;
void 			Fill_pDispBuf(Cptr str) ;
void 			Fill_pDispBuf(Cptr msg_chinese,Cptr msg_english) ;
void 			Fill_pDispBuf(bool force_eng , Cptr msg_chinese,Cptr msg_english) ;
void 			Fill_pDispBuf(Cptr msg_chinese,Cptr msg_english,Cptr msg_Italian) ;
void 			Fill_pDispBuf(bool force_eng ,Cptr msg_chinese,Cptr msg_english,Cptr msg_Italian) ;
void 			fill_proc_queue(void (*fnptr)(void *),void *dptr , char *fnname);
void   			FILL_WAIT_MOTOR_NEAR(ActTbl_t  *a_tbl ,uint16	&idx) ;
void   			FILL_WAIT_MOTOR_NEAR(ActTbl_t HUGE *a_tbl ,WORD	&idx) ;
void   			FILL_WAIT_MOTOR_NEAR(int32  npos,ActTbl_t  *a_tbl ,int32 dw[] ,uint16	no ,uint16	&idx) ;
void   			FILL_WAIT_MOTOR_NEAR(ProgType_t  *p_buf,ActTbl_t  *a_tbl ,int32  npos,uint16	&idx) ;
void   			FILL_WAIT_MOTOR_NEAR(ProgType_t HUGE *p_buf,ActTbl_t HUGE *a_tbl ,SDWORD  npos,WORD	&idx) ;
void   			FILL_WAIT_MOTOR_NEAR(SDWORD  npos,ActTbl_t HUGE *a_tbl ,SDWORD dw[] ,WORD	no ,WORD	&idx) ;
bool 			FillAxis_X(DWORD val,bool zero_space) ;
bool 			FillAxis_X(uint32 val,bool zero_space) ;
void 			FillErr() ;
int  			FillProgEnd(int fileno) ;
void 			FillToEnd (Cptr buf);
void 			FillToEndAir (Cptr buf) ;
void 			Filter_CHG_PAL() ;
uint16 			find_changepoint() ; 
WORD 			find_changepoint() ; 
void 			FirstPowerOn (bool alloc_off);
void 			FirstPowerOn (void);
void 			Flash (short idx);
void 			FLASH_COLOR_proc(void *dptr);
void 			FlashCursor (short idx);
void 			flush_proc_queue(void);
void 			flush_rs232();
void 			free_pat(void);
void 			G1RateMody (void);
void 			GainValMody (void);
void 			Gccyfile();
void 			GCodeMody (void);
void 			GComment() ;                                                                                 //
void 			Gen68KInterrupt (BYTE cmd);
void 			Gen68KInterrupt (uint8 cmd);
void 			gen_prog() ;
void 			GenSimTouch() ;
uint8 			Get3701Status (uint8 axis) ;
bool 			get_axisdate() ;
SDWORD 			get_dst_pos(BYTE axis,SDWORD dw ,  SDWORD lpos[] , SDWORD tlpos[]) ;
int32 			get_dst_pos(uint8 axis,int32 dw ,  int32 lpos[] , int32 tlpos[]) ;
int16 			get_XZRTSET() ;
BYTE 			Get_Zrt_io(BYTE axis) ;
uint8 			Get_Zrt_io(uint8 axis) ;
void 			GetCursor (uint16 field);
void 			GetCursor (WORD field);
uint8			GetKey (void);
uint8 			GetLastKey (void);
uint8 			GetNextKey (void);
void 			GetPalette(char huge *PalBuf) ;
void 			GetPalette(unsigned char *PalBuf) ;
void 			GetPalette(unsigned int start , unsigned int len , char huge *buf);
void 			GetPalette(unsigned int start , unsigned int len ,unsigned  char *buf);
void 			GetProgLine (short idx, char *buf);
uint8 			GetSign(ProgType_t  *p_buf,uint8 axis) ;
short 			GetStrLineWidth (char *str);
unsigned long 	GetTimer (short idx);
void 			GGraphfile() ;
void 			Grid2Unit(uint8 axis , int32 &d) ;
void 			Grid2Unit(BYTE axis , SDWORD &d) ;
void 			Grid2Unit_exact(uint8 axis , int32 &d) ;
void 			GRID_TO_CIR(BYTE axis,SDWORD &tt) ;
void 			GRID_TO_CIR(uint8 axis,int32 &tt) ;
void  			GRID_TO_DEG(BYTE axis,SDWORD &tt) ;
void 			GRID_TO_DEG(uint8 axis,int32 &tt) ;
void 			GRID_TO_MM(SDWORD &grid) ;
void 			GRID_TO_MM(uint8 axis,int32 &grid) ;
void 			HAND_SEL(uint8 axis) ;
void 			HandMov (BYTE axis, BYTE dir);
void 			HandMov (uint8 axis, uint8 dir);
void 			HELP_DOWN_proc(void * dptr);
void 			HELP_UP_proc(void *dptr);
void 			HelpContentUpDown_q (short step);
void 			HomeActive	(uint8 axis) ;
void 			HomeIntMody (void) ;
void 			HomeSeqMody (void);
void 			Idle (void);
void 			IDLE_RUN(void) ;
void 			idxMainMode(short& idx) ;
void 			ini_axis_str();
void 			ini_baud (UI mode);
void 			ini_lenchk_chart_00(void *dptr);
void 			ini_lenchk_chart_01(void *dptr);
void 			ini_pat(void);
void 			INI_Sprintf() ;
void 			ini_th_stopy() ;
void 			ini_zrt_power_on() ;
void 			iniComment() ;
void 			iniprodnoCMOS();
void 			Init3701 (void);
void 			Init3702 (void);
void 			init_8250();
void 			init_axis_table() ;
void 			init_com(uint8 no) ;
void 			Init_Graphic(void);
void 			Init_ints();
//void 			init_intvect(_go32_dpmi_seginfo *oint , UI intvecno,int(*isr)());
void 			init_isr(void);
void 			Init_KeyBoard() ;
void 			init_keyboard(void);
void 			Init_pc();
void 			Init_pc_common() ;
void 			init_proc_queue();
void 			init_record(void);
void 			init_rs232();
void 			init_rs_tr_buf();
void 			init_rs_tr_flg();
void 			init_var_table() ;
void 			InitAirTbl() ;
void 			InitChFont (void);
void  			InitChFont (void);
void 			InitChFontData(void) ;
void 			InitDynamicGlobal() ;
void 			InitializeTimer2() ;
void 			InitImageStack (void);
void 			InitIo (void);
void 			InitMotorIo (void);
void 			InitRollData (void);
void 			InitRunVar (void);
void 			InitScrn (short chk);
void 			InitVar (void);
void 			InsActiveProgLine (void);
void 			InsCurAirLine (void);
void 			InsCurProgLine (void);
void 			InstallClockIsr (void);
void 			InstallInterrupt (short irq_number, void ( *isr) (...));
void 			InstallInterrupt (short irq_number, void interrupt( far *isr) (...));
void 			int0b(...);
void 			int0c(...);
void 			int0d(...);
void 			interrupt far int0b(...);
void 			interrupt far int0c(...);
void 			interrupt far int0d(...);
int  			intHome();
int  			intTouch();
void 			invalid_num(SCRN_XY x , SCRN_XY y , COLOR_T color , int nochar , int size);
short 			IsFirstTag (void);
int  			IsFloppyReady(void) ;
void 			ISR_AUTO_RUN() ;
void 			ISR_FAST_RUN() ;
void 			isr_inport(void);
void 			isr_xdet(void);
void 			JumpLineMody (void);
void 			KeyAStart (void);
void 			KeyBStart (void);
void 			KeyCan (void);
void 			KeyChgCursor (void);
void 			KeyClrScreen (void);
void 			KeyClrY (void);
void 			KeyCopyFile (void);
void 			KeyCStart (void);
void 			KeyDot(void) ;
void 			KeyDown (void);
void 			KeyEndDegree (void);
void 			KeyError (void);
void 			KeyG0 (void);
void 			KeyG3Start (void);
void 			KeyG4Start (void);
void 			KeyG6Start (void);
void 			KeyGraphic() ;
void 			KeyHandA (void);
void 			KeyHandB (void);
void 			KeyHandC (void);
void 			KeyHandD (void);
void 			KeyHandLeft (void);
void 			KeyHandOff (void);
void 			KeyHandReset (void);
void 			KeyHandRight (void);
void 			KeyHandSW (void);
void 			KeyHandX (void);
void 			KeyHandX1 (void);
void 			KeyHandX10 (void);
void 			KeyHandX100 (void);
void 			KeyHandY (void);
void 			KeyHandZ (void);
void 			KeyHelp (void);
void 			KeyInNum (uint8 num);
bool 			KeyInNum_INDEX(uint8 num) ;
void 			KeyIns (void);
void 			Test_IO(uint8 keycode);
void 			Test_input(void);
void 			KeyIsr(void);
void 			HandIsr(void);
void 			Rs232_KeyIsr(void);
void 			KeyJmpnn(void) ;
void 			KeyKstep(void) ;
void 			KeyKstop(void) ;
void 			KeyLeft (void);
void 			KeyLoadFile (void);
void 			KeyManYScale (void);
void			KeyMinusA (void);
void			KeyMinusA_S (void);
void			KeyMinusB (void);
void 			KeyMinusC (void);
void 			KeyAirScrn (void);
void 			KeyCutter() ;

void 			KeyMinusD (void);
void			KeyMinusE (void);
void 			KeyMinusX (void);
void			KeyMinusY (void);
void			KeyMinusZ (void);
void 			KeyMotorASW (void);
void 			KeyMotorBSW (void);
void 			KeyMotorCSW (void);
void 			KeyMotorDSW (void) ;
void 			KeyMotorESW (void) ;
void 			KeyMotorYSW (void);
void 			KeyMotorZSW (void);
void 			KeyNum0 (void);
void 			KeyNum1 (void);
void 			KeyNum2 (void);
void 			KeyNum3 (void);
void 			KeyNum4 (void);
void 			KeyNum5 (void);
void 			KeyNum6 (void);
void 			KeyNum7 (void);
void 			KeyNum8 (void);
void 			KeyNum9 (void);
void 			KeyOil (void) ;
void 			KeyPgDown (void);
void 			KeyPgDown_INDEX_FILE_CURSOR() ;
void 			KeyPgUp (void);
void 			KeyPgUp_INDEX_FILE_CURSOR() ;
void			KeyPLUSA (void);
void			KeyPLUSA_S (void);
void			KeyPLUSB (void);
void			KeyPLUSC (void);
void			KeyPLUSD (void);
void 			KeyPLUSE (void);
void			KeyPLUSX (void);
void 			KeyPLUSY (void);
void			KeyPLUSZ (void);
void 			KeyPrinter (void);
void 			KeyProcMap (void);
void 			KeyProdno0 (void);
void 			KeyReach(void) ;
void 			KeyResReleased(void) ;
void 			KeyRight (void);
void 			KeyRun1(void) ;
void 			KeySafe (void);
void 			KeySaveFile (void);
void 			KeySetAir (void);
void 			KeySetGCode (void);
void 			KeySetPara (void);
void 			KeySetPara_nopass (void) ;
void 			KeySetProdno (void) ;
void 			KeySetSpeed (void) ;
void 			KeySetSpeedMode (void);
void 			KeySetT (void);
void 			KeySign (void);
void 			KeySpaceBar (void);
void 			KeySPD(void) ;
void 			KeySpecial(void) ;
void 			KeySpeedDec(void) ;
void 			KeySpeedInc(void) ;
void 			KeyStart (void);
void 			KeyStartDegree (void);
void 			KeyStep (void);
void 			KeyStop (void);
void 			KeySuspend (void);
void 			KeyTAxis (void);
void 			KeyTDelay (void);
void 			KeyTest (void);
void 			KeyTEST1(void) ;
void 			KeyUp (void);
void 			KeyWr (void);
void 			KeyNext (void);
void 			KeyMytest (void);
void 			KeyReturn (void);
void 			KeyY0 (void);
void 			KeyZrt (void);
void 			KeyZrtSet(void) ;
void 			KeyZStart (void);
void 			ldprodnoCMOS(DWORD *s);
void 			ldprodnoCMOS(uint32 *s);
void 			line256(SCRN_XY x1,SCRN_XY y1,SCRN_XY x2,SCRN_XY y2 ,  COLOR_T c);
void 			line256_q(SCRN_XY x1,SCRN_XY y1,SCRN_XY x2,SCRN_XY y2 , COLOR_T c);
void 			LINEMody (void);
void 			load_AGAP() ;
void 			load_AHome(void) ;
void 			load_AxisDelay(int idx) ;
void 			load_BATCH(void);
void 			load_BATCHn(void);
void 			load_BUZZER(void);
void 			load_cnt8254(void);
void 			load_config(void);
void 			load_config1(void);
void 			load_config10(void) ;
void 			load_config11(void) ;
void 			load_config12(void) ;
void 			load_config13(void) ;
void 			load_config14(void) ;
void 			load_config15(void) ;
void 			load_config16(void) ;
void 			load_config17(void) ;
void 			load_config18(void) ;
void 			load_config19(void) ;
void 			load_config2(void);
void 			load_config20(void) ;
void 			load_config21(void) ;
void 			load_config22(void) ;
void 			load_config23(void) ;
void 			load_config24(void) ;
void 			load_config25(void) ;
void 			load_config26(void) ;
void 			load_config3(void);
void 			load_config4(void);
void 			load_config5(void) ;
void 			load_config6(void) ;
void 			load_config7(void) ;
void 			load_config8(void) ;
void 			load_config9(void) ;
void MPG_X100Mody (void);
void 			load_config_all() ;
void 			load_config_backup(void) ;
void 			load_config_org(void) ;
void 			load_dec_dist(void);
void 			load_default_config(void) ;
void 			load_Delay(void);
void 			load_FAST(void);
void 			load_FEEDER() ;
void 			load_field(unsigned long floc , unsigned long len , BYTE *ptr) ;
void 			load_file(void);
void 			load_flag_virtual(void);
void 			load_G1Rate(int idx) ;
void 			load_g2comb(void);
void 			load_MPG_X100(void);
void 			save_MPG_X100(void);
void 			load_gain_val(void);
void 			load_home_seq(int idx);
void 			load_home_seq_d();
void 			load_HomeInt();
void 			load_language(void);
void 			load_man_gain(void);
void 			load_MANUFACTORY() ;
void 			load_manval(int idx);
void 			load_manval_d();
void 			load_motor_grads(int idx);
void 			load_MotorNEAR();
void 			load_MotorType();
void 			load_motorzabcsw(int axis);
void 			load_motorzabcsw_d();
void 			load_NEAR() ;
void 			load_NSN();
void 			load_OilOFF() ;
void 			load_OilON() ;
void 			load_ONE();
void 			load_Para1Val(int idx) ;
void 			load_PayOff(void) ;
void 			load_pos_zone(void);
void 			load_PRODPASS();
void 			load_Rate(int idx);
void 			load_Rate_d() ;
void 			load_repair_dst(void);
void 			load_repair_spd(void);
void 			load_RORDir() ;
void 			load_AEncoder() ;
void 			load_ROTQ_MDY() ;
void 			load_RUNDAYS();
void 			load_safe_sw(void) ;
void 			load_safety_door(void);
void 			load_ScrnSav(void);
void 			load_set_miss(void);
void 			load_set_quan(void);
void 			load_SIM_FAST() ;
void 			load_SimFast() ;
void 			load_SN(void) ;
void 			load_speed(int idx);
void 			load_speed_mode(void);
void 			load_SPEEDARR(int idx) ;
void 			load_SPIN_MDY();
void 			load_SPIN_ZRT() ;
void 			load_SwitchT() ;
void 			load_CutDist() ;
void 			load_TAIDAMotor(void);
void 			load_TIMER(void);
void 			load_ToPos(int idx) ;
void 			load_TOUCH_Y_NEAR() ;
void 			load_TouchInt();
void 			load_Type(void);
void 			load_Unit(int idx) ;
void 			load_UsbDisk();
void 			load_X_2016_Y0() ;
void 			load_X_2016_Y1();
void 			load_X_Encoder();
void 			load_X_SPD() ;
void 			load_xgrid_deg(void);
void 			load_Y0(void);
void 			load_Y1(void);
void 			load_Y_Encoder();
void 			load_y_suspend(void) ;
void 			load_YGAP() ;
void 			load_ZeroSpd(int idx);
void 			load_ZeroSpd_d();
void 			load_ZrtMode(int idx) ;
void 			load_ZRTSET(int idx) ;
void 			load_ENCR0(int idx) ;
void 			load_ENCR1(int idx) ;
short 			LoadBackupFile(uint16 file_no) ;
short 			LoadBackupFile(WORD file_no) ;
short 			LoadUSBFromFile (uint16 file_no, uint16 file_name);
void 			LoadFont(int no);
short 			LoadFromFile (long off, WORD size, char *name);
void 			loadGraph(uint16 file_no) ;
CursorData_t** 	LocSPDOK (void);
void 			LogoSw_q (short mode);
void 			LoopLineMody (void);
int 			m_rs232();
int  			m_rs232();
void 			m_x_spd(DWORD &tt) ;
void 			m_x_spd(uint32 &tt) ;
int  			main (void);
void 			make_virtual_move(int32 lpos[]) ;
void 			make_virtual_move(SDWORD lpos[]) ;
void 			make_virtual_move(ept_SDWORD lpos);
void 			MakeAirLine (uint16 disp_line, ProgType_t *prog);
void 			MakeAirLine (WORD disp_line, ProgType_t huge *prog);
uint16 			MakeAirTbl(short auto_fast, uint16 idx) ;
WORD 			MakeAirTbl(short auto_fast, WORD idx) ;
void 			MakeAirTitleStr (bool force_eng);
void 			MakeAutoActTbl (short mode);
void 			MakeEditTitleStr (bool force_eng);
char *			MakeFarPointer (char *p);
void 			MakeFastActTbl (short mode);
void 			MakeFieldYPos (CursorData_t **ptr);
short 			MakePasswordStr (Cptr buf);
short 			MakePasswordStr (ept_char buf);
//void 			MakeProgLine (uint16 disp_line, ProgType_t *prog);
//void 			MakeProgLine (WORD disp_line, ProgType_t huge *prog);
void 			MakeTitleStr(void) ;
void 			ManAirMody (void);
void 			ManGainMody (void);
void			ManMov (BYTE axis, BYTE dir,bool flag_delay);
void 			ManMov (uint8 axis, uint8 dir,bool flag_delay,uint8 hand_man);
void 			ManValMody (void);
void 			mdy_AXIS_A_Unit(void) ;
void 			mdy_axisz360(uint8 axis) ;
WORD 			mdy_BMOTORGRID_X() ;
uint16 			mdy_BMOTORGRID_X() ;
void 			mdy_cursor_by_unit();
void 			MdyActiveProgLine(int addval);
void 			MdyActiveProgLine_x(int addval);
void 			MdyCurProgLine(int addval);
bool 			mdyline() ;
void 			mednum(SCRN_XY x , SCRN_XY y , COLOR_T color , Cptr buf ,bool reverse,int8 pointpos );
void 			MessageMap (void);
void  			MM_TO_GRID(SDWORD &mm) ;
void 			MM_TO_GRID(uint8 axis,int32 &mm) ;
void 			motor_gradsMody (void);
void 			MOTOR_SW(BYTE axis) ;
void 			MOTOR_SW(uint8 axis) ;
void 			MotorCmd (BYTE axis, BYTE cmd,WORD dlycnt) ;
void 			MotorCmd (uint8 axis, uint8 cmd,uint16 dlycnt) ;
void 			MotorIsr (void);
void 			MotorNEARMody (void);
void 			MotorTypeMody (void);
bool 			mov_ZRT(BYTE axis);
bool 			mov_ZRT(uint8 axis);
void 			MOVE2S(ProgType_t  *p_buf,ActTbl_t  *a_tbl ,int32 dw[] ,	int32 lpos[], int32  &s, uint16 &idx	, uint32 ref,	uint16 no, uint16 line) ;
void 			MOVE2S(ProgType_t HUGE *p_buf,ActTbl_t HUGE *a_tbl ,SDWORD dw[] ,	SDWORD lpos[], SDWORD  &s, WORD &idx	, DWORD ref,	WORD no, WORD line) ;
void 			move_rotate(int ofs , int total , BYTE rotate_dir) ; 
void 			move_rotate(int ofs , int total , uint8 rotate_dir) ; 
void 			move_rotate_left_right( int total) ;
void 			move_rotate_left_right(char axis , int total);
void 			move_rotate_right_left( int total) ;
void 			move_rotate_right_left(char axis , int total);
void 			MoveHook(ActTbl_t *a_tbl ,int32 hook_s , int32 hook_e ,uint16 &idx , int32 xref  ) ;
void 			MoveHook(ActTbl_t HUGE *a_tbl ,SDWORD hook_s , SDWORD hook_e ,WORD &idx , SDWORD xref  );
short 			MovToZero(BYTE mode,BYTE axis); // mode :0 normal (ㄌ沮home_seg砞﹚)
short 			MovToZero(uint8 mode,uint8 axis);  	// mode :0 normal (ㄌ沮home_seg砞﹚)
short 			MovToZeroAll (short force);
void 			NEARMody (void) ;
void			NextCursor (void);
void 			NextCursor (void);
CursorData_t** 	NextCursorOK (void);
void 			ngetkey();
void 			NormalModyProc (void);
void 			NormalPostProc (void);
void 			NormalPrevProc (void);
void 			NSNMody (void) ;
int32 			Off3701Pos(int32 Start , int32 cur) ;
SDWORD 			Off3701Pos(SDWORD Start , SDWORD cur) ;
void 			off_dtr_rts();
BYTE			OFFSET_Y_dir(BYTE dir);
uint8 			OFFSET_Y_dir(uint8 dir);
void 			OilOFFMody (void) ;
void 			OilONMody (void) ;
void 			on_dtr_rts();
void 			ONEMody(void) ;
int 			open_config(char *filename , char *mode );
int 			open_config(char *mode );
int 			open_config_backup(char *mode) ;
int 			open_config_org(char *mode) ;
void 			open_dump_proc_queue(void);
void 			Para1ValMody (void);
void 			PauseClock (uint16 op_mode);
void 			PauseClock (WORD op_mode);
void 			PayOffMody (void) ;
void 			PICslaveMode(int mode);
void 			plot_lenchk(void *dptr);
short 			PopImage (short lx, short ly);
void 			PosZoneMody (void);
void 			PowerOff() ;
void			PrevCursor (void);
void 			PrevCursor (void);				
CursorData_t** 	PrevCursorOK (void);
CursorData_t**	nowCursorOK (void);
void 			PrinterAck (BYTE isok);
void 			PrinterAck (uint8 isok);
void 			PrinterBuf (short len, char *p);
void 			PrinterChar (char c, short len);
short 			PrinterEnd (void);
//void 			PRINTERFILE(FILE *fp_c) ;
//void 			PRINTERFILE(FILE *fp_c,FILE *fp_d) ;
short 			PrinterOK();
short 			PrinterProgram (void);
void 			PrinterStr (char *p);
short 			PrinterTitle (void);
short 			PrintString (SCRN_XY x, SCRN_XY y, COLOR_T fcol, COLOR_T bcol, Cptr fmt,...);
short 			PrintString (short x, short y, COLOR_T fcol, COLOR_T bcol, Cptr fmt,...);
short 			PrintStringLine (SCRN_XY x, SCRN_XY y, COLOR_T fcol, Cptr string);
short 			PrintStringLine (SCRN_XY x, SCRN_XY y, COLOR_T fcol, COLOR_T bcol, Cptr string);
void 			PrintStringLine1_proc(void *dptr) ;
short 			PrintStringLine_fmt (SCRN_XY x, SCRN_XY y, COLOR_T fcol, COLOR_T bcol, Cptr fmt, ...);
short 			PrintStringLine_fmt (SCRN_XY x, SCRN_XY y, COLOR_T fcol,  Cptr fmt, ...);
short 			PrintStringLine_fmt_q (SCRN_XY x, SCRN_XY y, COLOR_T fcol, COLOR_T bcol, Cptr fmt, ...);
short 			PrintStringLine_fmt_q (SCRN_XY x, SCRN_XY y, COLOR_T fcol, Cptr fmt, ...);
void 			PrintStringLine_q(SCRN_XY x, SCRN_XY y, COLOR_T fcol, COLOR_T bcol, Cptr string);
void 			PrintStringLine_q(SCRN_XY x, SCRN_XY y, COLOR_T fcol,Cptr string);
void 			sPrintStringLine_q(SCRN_XY x, SCRN_XY y, COLOR_T fcol, COLOR_T bcol, Cptr string);
void 			sPrintStringLine_q(SCRN_XY x, SCRN_XY y, COLOR_T fcol,Cptr string);
void 			PRN_BUF_proc(void *dptr);
void 			PRN_CHAR_proc(void *dptr);
void 			PRN_STR_proc(void *dptr);
short 			PrnBuf (char *p, short len);
short 			PrnChar (short c, short len);
short 			PrnStr (char *p);
void 			Probe(int i) ;
void 			process_config_org(uint8 key_help,uint8 key_wr) ;
void 			Prog2Air(bool save) ;
int 			Progaxis_no() ;
int  			Progaxis_no() ;
short 			PushImage (SCRN_XY lx, SCRN_XY ly, SCRN_XY rx, SCRN_XY ry);
short 			PushImage (short lx, short ly, short rx, short ry);
void 			PUTCHIN(SCRN_XY X,SCRN_XY Y, int IDX,COLOR_T COLOR);
void 			putdot(int x,int y );
void 			putdot(SCRN_XY x,SCRN_XY y );
void 			putdot_LENCHK(int x,int y);
void 			putdot_LENCHK(SCRN_XY x,SCRN_XY y);
void 			PutIcon (SCRN_XY lx, SCRN_XY ly, short idx, short op) ;
void 			PutIcon (short lx, short ly, short idx, short op);
void 			PutIcon_proc(void *dptr);
void 			PutIcon_q (SCRN_XY lx, SCRN_XY ly, short idx, short op);
void 			PutIcon_q (short lx, short ly, short idx, short op);
void 			quit_rs232();
void 			Rate1Mody (void) ;
void 			RateMody (void);
int  			rd_rs232();
int 			rd_rs232();
unsigned char  	rdCMOS(unsigned char addr );
bool 			rdflagStopRun() ;
uint32 			rdYYYYMMDD() ;
void 			Read_ZABCD_2016() ;
//short 			ReadDPProgLine (FILE *fp , uint16	num, ProgType_t	*data);
//short 			ReadDPProgLine (FILE *fp , WORD	num, ProgType_t	huge *data) ;
//short 			ReadDPProgLine (uint16 file_no, uint16 line, uint16 num, ProgType_t *data);
short 			ReadDPProgLine (WORD file_no, WORD line, WORD num, ProgType_t huge *data);
void 			ReadFileAck (BYTE isok, DWORD off, WORD size, BYTE *data);
void 			ReadFileAck (uint8 isok, uint32 off, uint16 size, uint8 *data);
short 			ReadFileBuf (char *filename ,long off, short size,char *data);
short 			ReadFullFile (short file_no);
void 			ReadIndexContent(uint16 fileno) ;
void 			ReadIndexContent(WORD fileno) ;
SDWORD 			ReadMov(BYTE axis);
int32 			ReadMov(uint8 axis);
SDWORD 			ReadReg3701 (BYTE axis, BYTE reg);
int32 			ReadReg3701 (uint8 axis, uint8 reg);
unsigned 		ReadTimer2() ;
void 			ready_PowerOff(BYTE loc) ;
void 			ready_PowerOff(uint8 loc) ;
void 			chk_off_power(BYTE loc) ;
void 			chk_off_power(uint8 loc) ;
void 			record_exetime(char *title);
void 			rectangle( short lx, short ly , short rx, short ry,COLOR_T color,short width);
void 			rectangle_border(COLOR_T color, short lx, short ly , short rx, short ry);
void 			rectangle_border_q(COLOR_T color, short lx, short ly , short rx, short ry);
void 			rectangle_fill(COLOR_T color, short lx, short ly , short rx, short ry) ;
void 			rectangle_fill_proc(void *dptr);
void 			rectangle_fill_q(COLOR_T color, short lx, short ly , short rx, short ry) ;
void 			rectangle_proc(void *dptr);
void 			rectangle_proc(void *dptr);		
void 			rectangle_q( short lx, short ly , short rx, short ry,COLOR_T color,short width) ;
void 			ReDrawEditWin_q (void);
void 			RedrawImage(void) ;
void 			ReMakeActTable (void);
void 			RepairDstMody (void);
void 			RepairSpdMody (void);
BYTE 			RepeatKey (BYTE ref_key, WORD repeat_no);
uint8 			RepeatKey (uint8 ref_key, uint16 repeat_no);
//void 			res_intvect(_go32_dpmi_seginfo *oint ,UI intvecno ) ;
void 			ResetKeyBuf (BYTE key);
void 			ResetKeyBuf (uint8 key);
void 			ReStart (BYTE axis);
void 			ReStart (uint8 axis);
void 			RestoreClock (BYTE key);
void 			RestoreClock (uint8 key);
void 			ReturnManMode (void);
void 			reverse_mov_ZRT(BYTE axis);
void 			reverse_mov_ZRT(uint8 axis);
void 			reverse_mov_ZRT_rotate(BYTE axis);
void 			reverse_mov_ZRT_rotate(uint8 axis) ;
void 			RInitImage (void);
void 			ROLL_OFF_proc(void *dptr);
void 			ROLL_ON_proc(void *dptr);
void 			ROTQ_MDYMody (void) ;
void 			RRealAxis(void) ;
void 			RUN_RUN(void) ;
void 			RunAirTbl (DWORD cur_x, BYTE mov_dir);
void 			RunAirTbl (uint32 cur_x, uint8 mov_dir);
void 			RunAutoActTbl (DWORD cur_x);
void 			RunAutoActTbl (uint32 cur_x);
void 			RunAutoStart (void);
void 			RUNDAYSMody (void);
void 			RunFastActTbl (DWORD cur_x);
void 			RunFastActTbl (uint32 cur_x);
void 			RunFastStart (void);
void 			safe_sensitivity() ;
void 			SafeErrStop (uint16 op_mode);
void 			SafeErrStop (WORD op_mode);
void 			SafetyDoorMody (void);
void 			save_AGAP() ;
void 			save_AHome(void) ;
void 			save_AxisDelay(int idx) ;
void 			save_BATCH(void);
void 			save_BATCHn(void);
void 			save_BUZZER(void);
void 			save_cnt8254(void);
void 			save_config(void);
void 			save_config1(void);
void 			save_config10(void) ;
void 			save_config11(void) ;
void 			save_config12(void) ;
void 			save_config13(void) ;
void 			save_config14(void) ;
void 			save_config15(void) ;
void 			save_config16(void) ;
void 			save_config17(void) ;
void 			save_config18(void) ;
void 			save_config19(void) ;
void 			save_config2(void);
void 			save_config20(void) ;
void 			save_config21(void) ;
void 			save_config22(void) ;
void 			save_config23(void) ;
void 			save_config24(void) ;
void 			save_config25(void) ;
void 			save_config26(void) ;
void 			save_config3(void);
void 			save_config4(void);
void 			save_config5(void);
void 			save_config6(void);
void 			save_config7(void) ;
void 			save_config7(void);
void 			save_config8(void) ;
void 			save_config8(void);
void 			save_config9(void) ;
void 			save_config_all(void) ;
void 			save_config_backup(void) ;
void 			save_config_org(void) ;
void 			save_dec_dist(void);
void 			save_Delay(void);
void 			save_FAST(void);
void 			save_FEEDER() ;
void 			save_field(unsigned long floc , unsigned long len , BYTE *ptr) ;
short 			FileN2File (WORD file_no, WORD file_name) ;
void 			save_file(void);
void 			save_flag_virtual(void);
void 			save_G1Rate(int idx) ;
void 			save_g2comb(void);
void 			save_gain_val(void);
void 			save_home_seq(int idx);
void 			save_home_seq_d();
void 			save_HomeInt();
void 			save_language(void);
void 			save_man_gain(void);
void 			save_MANUFACTORY();
void 			save_manval(int idx);
void 			save_manval_d();
void 			save_motor_grads(int idx);
void 			save_MotorNEAR();
void 			save_MotorType();
void 			save_motorzabcsw(int axis);
void 			save_motorzabcsw_d();
void 			save_NEAR() ;
void 			save_NSN();
void 			save_OilOFF() ;
void 			save_OilON() ;
void 			save_ONE();
void 			save_Para1Val(int idx);
void 			save_PayOff(void) ;
void 			save_pos_zone(void);
void 			save_PRODPASS();
void 			save_Rate(int idx);
void 			save_Rate_d();
void 			save_record(char *mes);
void 			save_repair_dst(void);
void 			save_repair_spd(void);
void 			save_RORDir() ;
void 			save_AEncoder() ;
void 			save_ROTQ_MDY();
void 			save_RUNDAYS();
void 			save_safe_sw(void) ;
void 			save_safety_door(void);
void 			save_ScrnSav(void);
void 			save_set_miss(void);
void 			save_set_quan(void);
void 			save_SIM_FAST() ;
void 			save_SimFast() ;
void 			save_SN(void) ;
void 			save_speed(int idx);
void 			save_speed_mode(void);
void 			save_SPEEDARR(int idx);
void 			save_SPIN_MDY();
void 			save_SPIN_ZRT() ;
void 			save_SwitchT() ;
void 			save_CutDist() ;
void 			save_TAIDAMotor(void);
void 			save_TIMER(void);
void 			save_ToPos(int idx) ;
void 			save_TOUCH_Y_NEAR() ;
void 			save_TouchInt();
void 			save_Type(void);
void 			save_Unit(int idx) ;
void 			save_UsbDisk();
void 			save_UsbDisk_KeyWr() ;
void 			save_X_2016_Y0();
void 			save_X_2016_Y1();
void 			save_X_Encoder();
void 			save_X_SPD() ;
void 			save_xgrid_deg(void);
void 			save_Y0(void);
void 			save_Y1(void);
void 			save_Y_Encoder();
void 			save_y_suspend(void) ;
void 			save_YGAP() ;
void 			save_ZeroSpd(int idx);
void 			save_ZeroSpd_d();
void 			save_ZrtMode(int idx) ;
void 			save_ZRTSET(int idx) ;
void 			save_ENCR0(int idx) ;
void 			save_ENCR1(int idx) ;
void 			SaveActiveProgLine(void);
void 			SaveAirLine(short start_line,short end_line);
short 			SaveBackupFile (uint16 file_no) ;
short 			SaveBackupFile (WORD file_no) ;
void 			SaveCurAirLine (void);
void 			SaveCurProgLine (void);
short 			FileN2file (uint16 file_no, uint16 file_name);
short 			FileN2file (WORD file_no, WORD file_name);
void 			saveGraph() ;
void 			SaveProgLine(short start_line,short end_line);
short 			SaveToFile (long off, WORD size, char *name);
void 			saveVGA(bool force);
void 			saveVGA(bool force,char filename[]) ;
void 			ScreenOnOff (short mode);
void 			SCRN_OFF_proc(void *dptr);
void 			SCRN_ON_proc(void *dptr);
void 			ScrnSavMody (void);
SDWORD 			sdDifGrid(BYTE axis , SDWORD s, SDWORD t) ;
int32 			sdDifGrid(int32 s, int32 t) ;
SDWORD 			sdDifGrid(SDWORD s, SDWORD t) ;
int32 			sdDifGrid(uint8 axis , int32 s, int32 t) ;
int32 			sdmdy_2016(uint8 axis,int32 d) ;
SDWORD 			sdmdy_2016(SDWORD d) ;
unsigned 		search_base();
DOS_ADDR 		search_base();
short 			SelfTest (void);
void 			SEND_PROG_proc(void *dptr);
void 			SendCmdZrt (BYTE axis, BYTE dir,short speed_factor);
void 			SendCmdZrt (uint8 axis, uint8 dir,short speed_factor);
void 			SendFlashColor_q (BYTE idx, COLOR_T col1, COLOR_T col2);
void 			SendFlashColor_q (uint8 idx, uint16 col1, uint16 col2);
short 			SendPrnBuf (char *p, uint16 len);
short 			SendPrnBuf (char *p, WORD len);
short 			SendPrnChar (char c, uint16 len);
short 			SendPrnChar (char c, WORD len);
short 			SendPrnStr (char *p);
void 			SendProgLine_q (uint16 idx, uint8 *buf);
void 			SendProgLine_q (WORD idx, BYTE *buf);
void 			SendProgList (void);
void 			SendSysInfo_q (void);
bool 			SendToArmCmd(BYTE cmd);
bool 			SendToArmCmd(uint8 cmd);
void 			SeqMody (void);
void 			Server_onoff(uint8 onoff) ;
void 			Server_onoff(uint8 axis ,uint8 onoff) ;
void 			Set3701 (uint8 axis, uint8 dir, int32 ref, int32 mov ,int32 rmov,bool run,int32 ymov,int idms);
void 			Set3701 (PHY_AXIS phy_axis, uint8 dir, uint32 ref, uint32 mov ,uint32 rmov,bool run,uint32 ymov);
void 			Set3701_67 (uint8 axis, uint8 dir, uint32 ref, uint32 mov ,uint32 rmov,bool run);
void 			Set3701ManMov (PHY_AXIS phy_axis, BYTE dir, DWORD ref, DWORD mov,bool amdyy);
void 			Set3701ManMov (uint8 axis, uint8 dir, int32 ref, int32 mov,bool amdyy);
void 			Set8254 (uint16 cnt);
void 			SET_A25000(void);
void 			SET_PASS_SCRN() ;
bool 			set_ScrnSav() ;
void 			SET_TOUCH_AIR(ProgType_t  *p_buf,ActTbl_t   *a_tbl , uint16	&idx, uint16 &air_idx	, int32	 &s, bool flag_ABC[],uint8 &e_air) ;
void 			SET_TOUCH_AIR(ProgType_t HUGE *p_buf,ActTbl_t  HUGE *a_tbl , WORD	&idx, WORD &air_idx	, SDWORD	 &s, bool flag_ABC[],BYTE &e_air) ;
void 			SET_TOUCH_AIR(ProgType_t HUGE *p_buf,ActTbl_t  HUGE *a_tbl , WORD	&idx, WORD &air_idx	, SDWORD	 &s, ept_bool flag_ABC,BYTE &e_air) ;
void 			SET_Type620(void);
void 			SET_ZABC3200_10000(void);
void 			set_zrt_power_on(BYTE axis) ;
void 			set_zrt_power_on(uint8 axis) ;
void 			SetAir(int8 airno,int8 set_clr) ;
void 			SetAllGain (uint8 val, uint8 m);
void 			SetAxisFlash() ;
void 			SetCCYMark (BYTE d);
void 			SetCCYMark (uint8 d);
void 			SetClock (short type);
Cptr 	 		SetColorE(Cptr buf) ;
Cptr 			SetColorE(ept_char buf);
void 			SetColorE(uint8 sign) ;
Cptr 			SetColorE(uint8 sign,Cptr buf) ;
Cptr 			SetColorE(uint8 sign,ept_char buf) ;
Cptr 			SetColorE_chgclr(Cptr buf) ;
Cptr 			SetColorS(COLOR_T fcol,COLOR_T bcol,Cptr buf) ;
Cptr 			SetColorS(COLOR_T fcol,COLOR_T bcol,ept_char  buf);
Cptr 			SetColorS(char seq ,Cptr psign,Cptr buf) ;				
void 			SetGcodeColorS(uint8 sign) ;	
void 			SetColorS(uint8 sign) ;
Cptr 			SetColorS(uint8 sign,Cptr buf) ;
void 			SetCursor (uint16 field);
void 			SetCursor (WORD field);
void 			SetFlash (short idx, COLOR_T col1, COLOR_T col2);
void 			SetLastKey(BYTE key) ;
void 			SetMachineStatusType() ;
void 			SetMissMody(void);
void 			SetMotorNEAR() ;
void 			SetMotorType() ;
void 			SetPalette( char huge *PalBuf) ;
void 			SetPalette( unsigned char  *PalBuf) ;
void 			SetPalette(unsigned int start , unsigned int len , char *buf);
void 			SetPalette(unsigned int start , unsigned int len , unsigned char *buf);
void 			SetProgFlash() ;
void 			SetProgTDelay (void);
void 			SetProgTouch (void);
void 			SetProgTouchAxis (void);
void 			SetProgValNull (void);
void 			SetQuanMody(void);
void 			SetSafeSwMode (short mode);
short 			SetStrColor (COLOR_T fcol, COLOR_T bcol, char *buf);
short 			SetStrColor (short fcol, short bcol, char *buf);
void 			setup_intHome(int Intno);
void 			setup_intHome(void) ;
void 			setup_intTouch(int Intno);
void 			setup_intTouch(void) ;
void 			SetupBATCHn() ;
short 			SetVideoMode (void);
void 			SetXEncoder() ;
void 			show16bmp() ;
void 			show16bmp_proc(void *dptr) ;
void 			show16bmp_q() ;
void 			showbmp(void) ;
void 			showbmp_help(int idx) ;
void 			ShowCursor (void);
void 			showmanval0() ;
void 			ShowMotorGrads_0 (BYTE axis) ;
void 			ShowMotorGrads_0 (uint8 axis) ;
void 			ShowNoFASTMode ();
void 			ShowRate_0 (BYTE axis) ;
void 			ShowRate_0 (uint8 axis) ;
void 			ShowRPM_0() ;
void 			ShowSafePower (BYTE b);
void 			ShowSafePower (uint8 b);
void 			ShowSafeSensor (BYTE b);
void 			ShowSafeSensor (uint8 b);
void 			ShowSafeTest (BYTE b);
void 			ShowSafeTest (uint8 b);
void 			ShowToHome () ;
void 			ShowTouchTest (BYTE b);
void 			ShowTouchTest (uint8 b);
void 			ShowToVirtualHome () ;
void 			ShowZeroSpd_0 (BYTE axis) ;
void 			ShowZeroSpd_0 (uint8 axis) ;
void 			SIM_FASTMody (void) ;
void 			SimFastMody (void) ;
void 			smallnum(int x , int y , int color , char *buf ,bool reverse , int8 pointpos );
void 			SoftReset (void);
void 			sort_airtbl(uint16 &idx) ;
void 			sort_airtbl(WORD &idx) ;
void 			sort_airtbl() ;
void 			SpeedMody (void);
void 			SPIN_MDYMody (void) ;
void 			SPIN_ZRTMody (void) ;
int 			Sprintf(char *fmt,...) ;
void 			Sprintf_next(char *fmt,...) ;
void			USBUpdate() ;
void 			FindSysDir(char Disk);
void 			FindDataDir(char Disk) ;
void 			start_Oil() ;
void 			StartRun (uint16 op_mode);
void			KeyStartRun() ;
unsigned char 	status_lenchk();
void 			StopMotor (uint8 axis);
void 			StopMotor(void) ;
void 			StopMotor_67 (uint8 axis);
uint16 			StrCpy (Cptr dst, Cptr src);		//盢src┮﹃йdst┮丁   肚:﹃
uint16          StrCpy (ept_char dst, Cptr src);
void 			strcpy_S (Cptr d,Cptr str) ;
uint16 			StrLen (Cptr str);//璸衡str┮﹃
uint16 			StrLen_S (Cptr str);
void 			svprodnoCMOS(DWORD *s);
void 			svprodnoCMOS(uint32 *s);
void 			svprodnoDisk(void) ;
void 			switch_next(char *str , BYTE *b) ;
void 			switch_next(char *str , uint8 *b) ;
void 			SwitchTMody (void) ;
void 			CutDistMody (void) ;
void 			SYS_INFO_proc(void *dptr);
void 			SysLangMody (void);
void 			SystemOff (void);
void 			SystemOff_proc(void *dptr);
void 			SystemOff_q() ;
void 			SystemOn (void);
void 			SystemOn_proc(void *dptr) ;
void 			SystemOn_q() ;
void 			TAIDAMotorMody (void) ;
void 			test_ascii1_19(void) ;
void 			test_axis(BYTE axis);
void 			test_axis(uint8 axis);
void 			test_const();
int 			test_endian();
int  			test_endian();
//FILE * 			test_fopen();
void 			test_home67();
void 			test_RdAxisA(void) ;
void 			test_stopmotor();
void 			test_timer0() ;
void 			test_trace_y() ;
void  			test_x() ;
void 			test_x() ;
bool 			th_chk_AB(unsigned no, unsigned touch);
int  			TimerIsr();
void 			TIMERMody (void);
void 			TO_GRID( BYTE axis, SDWORD &dw) ;
void 			TO_GRID( uint8 axis, int32 &dw) ;
void 			TO_GRID_NOT_ROTATE(  BYTE axis,SDWORD &dw) ;
void 			TO_GRID_NOT_ROTATE(  uint8 axis,int32 &dw) ;
void 			ToManProc (void);
void 			ToPosMody (void) ;
void 			touch2stop_axis(ProgType_t	 *p_buf,uint8 &th, uint8 &stop_axis) ;
void 			TOUCH_Y_NEARMody (void) ;
void 			TouchActive (short no);
void 			TouchErrStop (void);
void 			TouchIntMody (void) ;
void 			TouchIsr (void);
void 			tputchin(int x , int y , int color , int w , int h , unsigned char huge *buf );
void 			tputchin(int x , int y , int color , int w , int h , unsigned char  *buf );
void 			tputchin_00(void *dptr);
void 			TypeMody (void);
void 			unInstallClockIsr (void);
void 			unInstallInterrupt (short irq_number);
void 			unit_test(void ) ;
void 			UnitMody (void) ;
void 			update_flash() ;
void 			update_lenchk();
void 			update_lenchk_screen(void *dptr);
void 			update_lenchk_screen_00(void *dptr);
void 			update_lenchk_screen_01(void *dptr);
void 			update_lenchk_screen_01a(void *dptr);
void 			update_lenchk_screen_02(void *dptr);
void 			update_lenchk_screen_02a(void *dptr);
void 			update_lenchk_screen_02b(void *dptr);
void 			update_mednum(char *new_s , char *old_s ,int len,	int x1 , int y1 , int clr_text , int clr_bg,int8 pointpos);
void 			update_mednum(int new_val , char *old_s ,int len,	int x1 , int y1 , int clr_text , int clr_bg,int8 pointpos);
void 			update_roll() ;
void 			update_roll_q() ;
void 			update_sc();
void 			update_sc(bool force);
void 			update_sc_kernel() ;
void 			UPDATE_SCROLL_BAR_proc(void *dptr);
void 			update_system() ;
void 			UpdatePageProg (uint16 cur_line);
void 			UpdateScrollBar_proc(void *dptr);
void 			UpdateScrollBar_q (uint16 percent);
void 			USB_PowerOff(bool usbflg) ;
void 			UsbDiskMody (void) ;
bool 			Verify_PRODPASS(uint32 prodpass) ;
void 			Verify_th(uint16 line) ;
short 			VerifyAir(uint16 *errline) ;
short 			VerifyAir(WORD *errline) ;
short 			VerifyAutoProg (uint16 *errline,bool check_z);
short 			VerifyFastProg (uint16 *errline, bool check_z);
short 			VerifyProg (short speed_mode , bool check_z);
short		 	VerifyProg (short speed_mode , bool check_z,bool inReMakeActTable);
void 			virtual_move(bool in_isr ) ;
void 			Wait3701 (uint8 axis);
void 			WAIT_NEW_KEY(char &code) ;
void 			WAIT_NEW_KEY(void) ;
void 			WAIT_NEW_KEY_SAME(void) ;
void 			WAIT_RUN_TEST_KEY(BYTE type,BYTE ErrorCode) ;
void 			WAIT_RUN_TEST_KEY(uint8 type) ;
void 			WaitMotorNear(uint16 &cnt ,uint8 axis,uint32 NEARCNT_MAX) ;
void 			WaitMotorNear(WORD &cnt ,BYTE axis,DWORD NEARCNT_MAX) ;
BYTE 			WaitR_CMD(DOS_ADDR base,BYTE	axis, BYTE (*chk_fun)(BYTE ),char *mes,DWORD loop_times, BYTE cmd) ;
BYTE 			WaitR_CMD(DOS_ADDR addr,PHY_AXIS	phy_axis, BYTE (*chk_fun)(BYTE ),char *mes,DWORD loop_times,DOS_ADDR W_CMD_addr, BYTE cmd) ;
uint8 			WaitR_CMD(unsigned addr,uint8	axis, uint8 (*chk_fun)(uint8 ),char *mes,uint32 loop_times) ;
SWORD 			WBcdAddBin (BYTE *sign, WORD *bcdval, SWORD binval);
int16 			WBcdAddBin (uint8 *sign, uint16 *bcdval, int16 binval);
void 			WireOnOff (BYTE on);
void 			WireOnOff (uint8 on);
void 			wr_rs232(UC ch);
void 			wrCMOS(unsigned char addr , unsigned char data);
uint16 			wRead2016 (uint8 axis);
short 			WriteDPProgLine (uint16 file_no, uint16 line, uint16 num, ProgType_t *data);
void 			WriteFileAck (BYTE isok, DWORD off, WORD size);
void 			WriteFileAck (uint8 isok, uint32 off, uint16 size);
short 			FileN2Buf (char *FileNname , long off, short size, char *data);
void 			X_2016_Y0Mody(void) ;
void 			X_2016_Y1Mody(void) ;
void 			X_EncoderMody (void);
void 			X_SPDMody (void) ;
void 			XDegreeMody (void);
int32 			XGrid2HookGrid(int32 x) ;
SDWORD 			XGrid2HookGrid(SDWORD x) ;
void 			Y0Mody (void);
void 			Y1Mody (void);
void 			Y_EncoderMody (void);
void 			YGAPMody (void) ;
void 			YGridMmMody (void);
void 			ZeroSpdMody (void) ;
void 			ZrtModeMody (void) ;
void 			ZRTSETMody (void) ;
void 			ENCR0Mody (void) ;
void 			ENCR1Mody (void) ;
void 			main_ExeMode(char *argvx[]);
void sendError(uint8 Cmd,int no,int len);
void sendCmd(uint8 Cmd,uint8 buf[],int len);
void SendKey(BYTE keycode);
void SendStatus();
