EXTERN CursorData_t	X_ENCR0_CUR		  
#ifdef GLOBAL
	N_ENCR0_CUR(0)
#endif
;

EXTERN CursorData_t	Y_ENCR0_CUR		  
#ifdef GLOBAL
	N_ENCR0_CUR(1)
#endif
;

EXTERN CursorData_t	Z_ENCR0_CUR		  
#ifdef GLOBAL
	N_ENCR0_CUR(2)
#endif
;

EXTERN CursorData_t	A_ENCR0_CUR		  
#ifdef GLOBAL
	N_ENCR0_CUR(3)
#endif
;

EXTERN CursorData_t	B_ENCR0_CUR		  
#ifdef GLOBAL
	N_ENCR0_CUR(4)
#endif
;

EXTERN CursorData_t	C_ENCR0_CUR		  
#ifdef GLOBAL
	N_ENCR0_CUR(5)
#endif
;

EXTERN CursorData_t	D_ENCR0_CUR		  
#ifdef GLOBAL
	N_ENCR0_CUR(6)
#endif
;

EXTERN CursorData_t	E_ENCR0_CUR		  
#ifdef GLOBAL
	N_ENCR0_CUR(7)
#endif
;
