EXTERN CursorData_t	X_ENCR1_CUR		  
#ifdef GLOBAL
	N_ENCR1_CUR(0)
#endif
;

EXTERN CursorData_t	Y_ENCR1_CUR		  
#ifdef GLOBAL
	N_ENCR1_CUR(1)
#endif
;

EXTERN CursorData_t	Z_ENCR1_CUR		  
#ifdef GLOBAL
	N_ENCR1_CUR(2)
#endif
;

EXTERN CursorData_t	A_ENCR1_CUR		  
#ifdef GLOBAL
	N_ENCR1_CUR(3)
#endif
;

EXTERN CursorData_t	B_ENCR1_CUR		  
#ifdef GLOBAL
	N_ENCR1_CUR(4)
#endif
;

EXTERN CursorData_t	C_ENCR1_CUR		  
#ifdef GLOBAL
	N_ENCR1_CUR(5)
#endif
;

EXTERN CursorData_t	D_ENCR1_CUR		  
#ifdef GLOBAL
	N_ENCR1_CUR(6)
#endif
;

EXTERN CursorData_t	E_ENCR1_CUR		  
#ifdef GLOBAL
	N_ENCR1_CUR(7)
#endif
;


