


EXTERN CursorData_t	G1RATE_X_CUR
#ifdef GLOBAL
	G1RATE_N_CUR(0)
#endif
;

EXTERN CursorData_t	G1RATE_Y_CUR
#ifdef GLOBAL
	G1RATE_N_CUR(1)
#endif
;

EXTERN CursorData_t	G1RATE_Z_CUR		  
#ifdef GLOBAL
	G1RATE_N_CUR(2)
#endif
;

EXTERN CursorData_t	G1RATE_A_CUR		  
#ifdef GLOBAL
	G1RATE_N_CUR(3)
#endif
;

EXTERN CursorData_t	G1RATE_B_CUR		  
#ifdef GLOBAL
	G1RATE_N_CUR(4)
#endif
;

EXTERN CursorData_t	G1RATE_C_CUR		  
#ifdef GLOBAL
	G1RATE_N_CUR(5)
#endif
;
EXTERN CursorData_t	G1RATE_D_CUR		  
#ifdef GLOBAL
	G1RATE_N_CUR(6)
#endif
;

EXTERN CursorData_t	G1RATE_E_CUR		  
#ifdef GLOBAL
	G1RATE_N_CUR(7)
#endif
;

