EXTERN CursorData_t	X_GEAR1_CUR		  
#ifdef GLOBAL
	N_GEAR1_CUR(0)
#endif
;

EXTERN CursorData_t	Y_GEAR1_CUR		  
#ifdef GLOBAL
	N_GEAR1_CUR(1)
#endif
;

EXTERN CursorData_t	Z_GEAR1_CUR		  
#ifdef GLOBAL
	N_GEAR1_CUR(2)
#endif
;

EXTERN CursorData_t	A_GEAR1_CUR		  
#ifdef GLOBAL
	N_GEAR1_CUR(3)
#endif
;

EXTERN CursorData_t	B_GEAR1_CUR		  
#ifdef GLOBAL
	N_GEAR1_CUR(4)
#endif
;

EXTERN CursorData_t	C_GEAR1_CUR		  
#ifdef GLOBAL
	N_GEAR1_CUR(5)
#endif
;

EXTERN CursorData_t	D_GEAR1_CUR		  
#ifdef GLOBAL
	N_GEAR1_CUR(6)
#endif
;

EXTERN CursorData_t	E_GEAR1_CUR		  
#ifdef GLOBAL
	N_GEAR1_CUR(7)
#endif
;
