EXTERN CursorData_t	X_GEAR0_CUR		  
#ifdef GLOBAL
	N_GEAR0_CUR(0)
#endif
;

EXTERN CursorData_t	Y_GEAR0_CUR		  
#ifdef GLOBAL
	N_GEAR0_CUR(1)
#endif
;

EXTERN CursorData_t	Z_GEAR0_CUR		  
#ifdef GLOBAL
	N_GEAR0_CUR(2)
#endif
;

EXTERN CursorData_t	A_GEAR0_CUR		  
#ifdef GLOBAL
	N_GEAR0_CUR(3)
#endif
;

EXTERN CursorData_t	B_GEAR0_CUR		  
#ifdef GLOBAL
	N_GEAR0_CUR(4)
#endif
;

EXTERN CursorData_t	C_GEAR0_CUR		  
#ifdef GLOBAL
	N_GEAR0_CUR(5)
#endif
;

EXTERN CursorData_t	D_GEAR0_CUR		  
#ifdef GLOBAL
	N_GEAR0_CUR(6)
#endif
;

EXTERN CursorData_t	E_GEAR0_CUR		  
#ifdef GLOBAL
	N_GEAR0_CUR(7)
#endif
;
