EXTERN CursorData_t	X_GRID_CUR
#ifdef GLOBAL
	N_GRID_CUR(0)
#endif
;

EXTERN CursorData_t	Y_GRID_CUR
#ifdef GLOBAL
	N_GRID_CUR(1)
#endif
;

EXTERN CursorData_t	Z_GRID_CUR
#ifdef GLOBAL
	N_GRID_CUR(2)
#endif
;

EXTERN CursorData_t	A_GRID_CUR
#ifdef GLOBAL
	N_GRID_CUR(3)
#endif
;

EXTERN CursorData_t	B_GRID_CUR
#ifdef GLOBAL
	N_GRID_CUR(4)
#endif
;

EXTERN CursorData_t	C_GRID_CUR		  
#ifdef GLOBAL
	N_GRID_CUR(5)
#endif
;

EXTERN CursorData_t	D_GRID_CUR		  
#ifdef GLOBAL
	N_GRID_CUR(6)
#endif
;

EXTERN CursorData_t	E_GRID_CUR		  
#ifdef GLOBAL
	N_GRID_CUR(7)
#endif
;

