


EXTERN CursorData_t	IDMS_X_CUR
#ifdef GLOBAL
	IDMS_N_CUR(0)
#endif
;

EXTERN CursorData_t	IDMS_Y_CUR
#ifdef GLOBAL
	IDMS_N_CUR(1)
#endif
;

EXTERN CursorData_t	IDMS_Z_CUR		  
#ifdef GLOBAL
	IDMS_N_CUR(2)
#endif
;

EXTERN CursorData_t	IDMS_A_CUR		  
#ifdef GLOBAL
	IDMS_N_CUR(3)
#endif
;

EXTERN CursorData_t	IDMS_B_CUR		  
#ifdef GLOBAL
	IDMS_N_CUR(4)
#endif
;

EXTERN CursorData_t	IDMS_C_CUR		  
#ifdef GLOBAL
	IDMS_N_CUR(5)
#endif
;
EXTERN CursorData_t	IDMS_D_CUR		  
#ifdef GLOBAL
	IDMS_N_CUR(6)
#endif
;

EXTERN CursorData_t	IDMS_E_CUR		  
#ifdef GLOBAL
	IDMS_N_CUR(7)
#endif
;

