EXTERN CursorData_t	X_LOWSPD_CUR		  
#ifdef GLOBAL
	N_LOWSPD_CUR(0)
#endif
;

EXTERN CursorData_t	Y_LOWSPD_CUR		  
#ifdef GLOBAL
	N_LOWSPD_CUR(1)
#endif
;

EXTERN CursorData_t	Z_LOWSPD_CUR		  
#ifdef GLOBAL
	N_LOWSPD_CUR(2)
#endif
;

EXTERN CursorData_t	A_LOWSPD_CUR		  
#ifdef GLOBAL
	N_LOWSPD_CUR(3)
#endif
;

EXTERN CursorData_t	B_LOWSPD_CUR		  
#ifdef GLOBAL
	N_LOWSPD_CUR(4)
#endif
;

EXTERN CursorData_t	C_LOWSPD_CUR		  
#ifdef GLOBAL
	N_LOWSPD_CUR(5)
#endif
;

EXTERN CursorData_t	D_LOWSPD_CUR		  
#ifdef GLOBAL
	N_LOWSPD_CUR(6)
#endif
;

EXTERN CursorData_t	E_LOWSPD_CUR		  
#ifdef GLOBAL
	N_LOWSPD_CUR(7)
#endif
;

