EXTERN CursorData_t	X_Max_CUR		  
#ifdef GLOBAL
	N_Max_CUR(0)
#endif
;

EXTERN CursorData_t	Y_Max_CUR		  
#ifdef GLOBAL
	N_Max_CUR(1)
#endif
;

EXTERN CursorData_t	Z_Max_CUR		  
#ifdef GLOBAL
	N_Max_CUR(2)
#endif
;

EXTERN CursorData_t	A_Max_CUR		  
#ifdef GLOBAL
	N_Max_CUR(3)
#endif
;

EXTERN CursorData_t	B_Max_CUR		  
#ifdef GLOBAL
	N_Max_CUR(4)
#endif
;

EXTERN CursorData_t	C_Max_CUR		  
#ifdef GLOBAL
	N_Max_CUR(5)
#endif
;

EXTERN CursorData_t	D_Max_CUR		  
#ifdef GLOBAL
	N_Max_CUR(6)
#endif
;

EXTERN CursorData_t	E_Max_CUR		  
#ifdef GLOBAL
	N_Max_CUR(7)
#endif
;
