EXTERN CursorData_t	X_Min_CUR		  
#ifdef GLOBAL
	N_Min_CUR(0)
#endif
;

EXTERN CursorData_t	Y_Min_CUR		  
#ifdef GLOBAL
	N_Min_CUR(1)
#endif
;

EXTERN CursorData_t	Z_Min_CUR		  
#ifdef GLOBAL
	N_Min_CUR(2)
#endif
;

EXTERN CursorData_t	A_Min_CUR		  
#ifdef GLOBAL
	N_Min_CUR(3)
#endif
;

EXTERN CursorData_t	B_Min_CUR		  
#ifdef GLOBAL
	N_Min_CUR(4)
#endif
;

EXTERN CursorData_t	C_Min_CUR		  
#ifdef GLOBAL
	N_Min_CUR(5)
#endif
;

EXTERN CursorData_t	D_Min_CUR		  
#ifdef GLOBAL
	N_Min_CUR(6)
#endif
;

EXTERN CursorData_t	E_Min_CUR		  
#ifdef GLOBAL
	N_Min_CUR(7)
#endif
;
