EXTERN CursorData_t	X_MOTOR_TYPE_CUR
#ifdef GLOBAL
	N_MOTOR_TYPE_CUR(0)
#endif
;

EXTERN CursorData_t	Y_MOTOR_TYPE_CUR
#ifdef GLOBAL
	N_MOTOR_TYPE_CUR(1)
#endif
;

EXTERN CursorData_t	Z_MOTOR_TYPE_CUR
#ifdef GLOBAL
	N_MOTOR_TYPE_CUR(2)
#endif
;

EXTERN CursorData_t	A_MOTOR_TYPE_CUR
#ifdef GLOBAL
	N_MOTOR_TYPE_CUR(3)
#endif
;

EXTERN CursorData_t	B_MOTOR_TYPE_CUR
#ifdef GLOBAL
	N_MOTOR_TYPE_CUR(4)
#endif
;

EXTERN CursorData_t	C_MOTOR_TYPE_CUR		  
#ifdef GLOBAL
	N_MOTOR_TYPE_CUR(5)
#endif
;

EXTERN CursorData_t	D_MOTOR_TYPE_CUR		  
#ifdef GLOBAL
	N_MOTOR_TYPE_CUR(6)
#endif
;

EXTERN CursorData_t	E_MOTOR_TYPE_CUR		  
#ifdef GLOBAL
	N_MOTOR_TYPE_CUR(7)
#endif
;

