EXTERN CursorData_t	X_MotorNEAR_CUR		  
#ifdef GLOBAL
	N_MotorNEAR_CUR(0)
#endif
;

EXTERN CursorData_t	Y_MotorNEAR_CUR		  
#ifdef GLOBAL
	N_MotorNEAR_CUR(1)
#endif
;

EXTERN CursorData_t	Z_MotorNEAR_CUR		  
#ifdef GLOBAL
	N_MotorNEAR_CUR(2)
#endif
;

EXTERN CursorData_t	A_MotorNEAR_CUR		  
#ifdef GLOBAL
	N_MotorNEAR_CUR(3)
#endif
;

EXTERN CursorData_t	B_MotorNEAR_CUR		  
#ifdef GLOBAL
	N_MotorNEAR_CUR(4)
#endif
;

EXTERN CursorData_t	C_MotorNEAR_CUR		  
#ifdef GLOBAL
	N_MotorNEAR_CUR(5)
#endif
;

EXTERN CursorData_t	D_MotorNEAR_CUR		  
#ifdef GLOBAL
	N_MotorNEAR_CUR(6)
#endif
;

EXTERN CursorData_t	E_MotorNEAR_CUR		  
#ifdef GLOBAL
	N_MotorNEAR_CUR(7)
#endif
;
