EXTERN CursorData_t	X_NY0_CUR		  
#ifdef GLOBAL
	N_NY0_CUR(0)
#endif
;

EXTERN CursorData_t	Y_NY0_CUR		  
#ifdef GLOBAL
	N_NY0_CUR(1)
#endif
;

EXTERN CursorData_t	Z_NY0_CUR		  
#ifdef GLOBAL
	N_NY0_CUR(2)
#endif
;

EXTERN CursorData_t	A_NY0_CUR		  
#ifdef GLOBAL
	N_NY0_CUR(3)
#endif
;

EXTERN CursorData_t	B_NY0_CUR		  
#ifdef GLOBAL
	N_NY0_CUR(4)
#endif
;

EXTERN CursorData_t	C_NY0_CUR		  
#ifdef GLOBAL
	N_NY0_CUR(5)
#endif
;

EXTERN CursorData_t	D_NY0_CUR		  
#ifdef GLOBAL
	N_NY0_CUR(6)
#endif
;

EXTERN CursorData_t	E_NY0_CUR		  
#ifdef GLOBAL
	N_NY0_CUR(7)
#endif
;


