


EXTERN CursorData_t	RATE_X_CUR
#ifdef GLOBAL
	RATE_N_CUR(0)
#endif
;

EXTERN CursorData_t	RATE_Y_CUR
#ifdef GLOBAL
	RATE_N_CUR(1)
#endif
;

EXTERN CursorData_t	RATE_Z_CUR		  
#ifdef GLOBAL
	RATE_N_CUR(2)
#endif
;

EXTERN CursorData_t	RATE_A_CUR		  
#ifdef GLOBAL
	RATE_N_CUR(3)
#endif
;

EXTERN CursorData_t	RATE_B_CUR		  
#ifdef GLOBAL
	RATE_N_CUR(4)
#endif
;

EXTERN CursorData_t	RATE_C_CUR		  
#ifdef GLOBAL
	RATE_N_CUR(5)
#endif
;
EXTERN CursorData_t	RATE_D_CUR
#ifdef GLOBAL
	RATE_N_CUR(6)
#endif
;

EXTERN CursorData_t	RATE_E_CUR
#ifdef GLOBAL
	RATE_N_CUR(7)
#endif
;
