EXTERN CursorData_t	X_SPDFun_CUR		  
#ifdef GLOBAL
	N_SPDFun_CUR(0)
#endif
;

EXTERN CursorData_t	Y_SPDFun_CUR		  
#ifdef GLOBAL
	N_SPDFun_CUR(1)
#endif
;

EXTERN CursorData_t	Z_SPDFun_CUR		  
#ifdef GLOBAL
	N_SPDFun_CUR(2)
#endif
;

EXTERN CursorData_t	A_SPDFun_CUR		  
#ifdef GLOBAL
	N_SPDFun_CUR(3)
#endif
;

EXTERN CursorData_t	B_SPDFun_CUR		  
#ifdef GLOBAL
	N_SPDFun_CUR(4)
#endif
;

EXTERN CursorData_t	C_SPDFun_CUR		  
#ifdef GLOBAL
	N_SPDFun_CUR(5)
#endif
;

EXTERN CursorData_t	D_SPDFun_CUR		  
#ifdef GLOBAL
	N_SPDFun_CUR(6)
#endif
;

EXTERN CursorData_t	E_SPDFun_CUR		  
#ifdef GLOBAL
	N_SPDFun_CUR(7)
#endif
;

