EXTERN CursorData_t	X_SPDMinus_CUR		  
#ifdef GLOBAL
	N_SPDMinus_CUR(0)
#endif
;

EXTERN CursorData_t	Y_SPDMinus_CUR		  
#ifdef GLOBAL
	N_SPDMinus_CUR(1)
#endif
;

EXTERN CursorData_t	Z_SPDMinus_CUR		  
#ifdef GLOBAL
	N_SPDMinus_CUR(2)
#endif
;

EXTERN CursorData_t	A_SPDMinus_CUR		  
#ifdef GLOBAL
	N_SPDMinus_CUR(3)
#endif
;

EXTERN CursorData_t	B_SPDMinus_CUR		  
#ifdef GLOBAL
	N_SPDMinus_CUR(4)
#endif
;

EXTERN CursorData_t	C_SPDMinus_CUR		  
#ifdef GLOBAL
	N_SPDMinus_CUR(5)
#endif
;

EXTERN CursorData_t	D_SPDMinus_CUR		  
#ifdef GLOBAL
	N_SPDMinus_CUR(6)
#endif
;

EXTERN CursorData_t	E_SPDMinus_CUR		  
#ifdef GLOBAL
	N_SPDMinus_CUR(7)
#endif
;
