EXTERN CursorData_t	X_SPDPlus_CUR		  
#ifdef GLOBAL
	N_SPDPlus_CUR(0)
#endif
;

EXTERN CursorData_t	Y_SPDPlus_CUR		  
#ifdef GLOBAL
	N_SPDPlus_CUR(1)
#endif
;

EXTERN CursorData_t	Z_SPDPlus_CUR		  
#ifdef GLOBAL
	N_SPDPlus_CUR(2)
#endif
;

EXTERN CursorData_t	A_SPDPlus_CUR		  
#ifdef GLOBAL
	N_SPDPlus_CUR(3)
#endif
;

EXTERN CursorData_t	B_SPDPlus_CUR		  
#ifdef GLOBAL
	N_SPDPlus_CUR(4)
#endif
;

EXTERN CursorData_t	C_SPDPlus_CUR		  
#ifdef GLOBAL
	N_SPDPlus_CUR(5)
#endif
;

EXTERN CursorData_t	D_SPDPlus_CUR		  
#ifdef GLOBAL
	N_SPDPlus_CUR(6)
#endif
;

EXTERN CursorData_t	E_SPDPlus_CUR		  
#ifdef GLOBAL
	N_SPDPlus_CUR(7)
#endif
;

