EXTERN CursorData_t	X_TOPOS_CUR		  
#ifdef GLOBAL
	N_TOPOS_CUR(0)
#endif
;

EXTERN CursorData_t	Y_TOPOS_CUR		  
#ifdef GLOBAL
	N_TOPOS_CUR(1)
#endif
;

EXTERN CursorData_t	Z_TOPOS_CUR		  
#ifdef GLOBAL
	N_TOPOS_CUR(2)
#endif
;

EXTERN CursorData_t	A_TOPOS_CUR		  
#ifdef GLOBAL
	N_TOPOS_CUR(3)
#endif
;

EXTERN CursorData_t	B_TOPOS_CUR		  
#ifdef GLOBAL
	N_TOPOS_CUR(4)
#endif
;

EXTERN CursorData_t	C_TOPOS_CUR		  
#ifdef GLOBAL
	N_TOPOS_CUR(5)
#endif
;
EXTERN CursorData_t	D_TOPOS_CUR		  
#ifdef GLOBAL
	N_TOPOS_CUR(6)
#endif
;
EXTERN CursorData_t	E_TOPOS_CUR		  
#ifdef GLOBAL
	N_TOPOS_CUR(7)
#endif
;
