EXTERN CursorData_t	X_UNIT_CUR		  
#ifdef GLOBAL
		N_UNIT_CUR(0)
#endif
;

EXTERN CursorData_t	Y_UNIT_CUR		  
#ifdef GLOBAL
		N_UNIT_CUR(1)
#endif
;

EXTERN CursorData_t	Z_UNIT_CUR		  
#ifdef GLOBAL
		N_UNIT_CUR(2)
#endif
;

EXTERN CursorData_t	A_UNIT_CUR		  
#ifdef GLOBAL
		N_UNIT_CUR(3)
#endif
;

EXTERN CursorData_t	B_UNIT_CUR		  
#ifdef GLOBAL
		N_UNIT_CUR(4)
#endif
;

EXTERN CursorData_t	C_UNIT_CUR
#ifdef GLOBAL
		N_UNIT_CUR(5)
#endif
;

EXTERN CursorData_t	D_UNIT_CUR
#ifdef GLOBAL
		N_UNIT_CUR(6)
#endif
;

EXTERN CursorData_t	E_UNIT_CUR
#ifdef GLOBAL
		N_UNIT_CUR(7)
#endif
;
