EXTERN CursorData_t	X_ZRTSET_CUR		  
#ifdef GLOBAL
	N_ZRTSET_CUR(0)
#endif
;

EXTERN CursorData_t	Y_ZRTSET_CUR		  
#ifdef GLOBAL
	N_ZRTSET_CUR(1)
#endif
;

EXTERN CursorData_t	Z_ZRTSET_CUR		  
#ifdef GLOBAL
	N_ZRTSET_CUR(2)
#endif
;

EXTERN CursorData_t	A_ZRTSET_CUR		  
#ifdef GLOBAL
	N_ZRTSET_CUR(3)
#endif
;

EXTERN CursorData_t	B_ZRTSET_CUR		  
#ifdef GLOBAL
	N_ZRTSET_CUR(4)
#endif
;

EXTERN CursorData_t	C_ZRTSET_CUR		  
#ifdef GLOBAL
	N_ZRTSET_CUR(5)
#endif
;

EXTERN CursorData_t	D_ZRTSET_CUR		  
#ifdef GLOBAL
	N_ZRTSET_CUR(6)
#endif
;

EXTERN CursorData_t	E_ZRTSET_CUR		  
#ifdef GLOBAL
	N_ZRTSET_CUR(7)
#endif
;
