EXTERN CursorData_t	X_ZRTPreM_CUR		  
#ifdef GLOBAL
	N_ZRTPreM_CUR(0)
#endif
;

EXTERN CursorData_t	Y_ZRTPreM_CUR		  
#ifdef GLOBAL
	N_ZRTPreM_CUR(1)
#endif
;

EXTERN CursorData_t	Z_ZRTPreM_CUR		  
#ifdef GLOBAL
	N_ZRTPreM_CUR(2)
#endif
;

EXTERN CursorData_t	A_ZRTPreM_CUR		  
#ifdef GLOBAL
	N_ZRTPreM_CUR(3)
#endif
;

EXTERN CursorData_t	B_ZRTPreM_CUR		  
#ifdef GLOBAL
	N_ZRTPreM_CUR(4)
#endif
;

EXTERN CursorData_t	C_ZRTPreM_CUR		  
#ifdef GLOBAL
	N_ZRTPreM_CUR(5)
#endif
;

EXTERN CursorData_t	D_ZRTPreM_CUR		  
#ifdef GLOBAL
	N_ZRTPreM_CUR(6)
#endif
;

EXTERN CursorData_t	E_ZRTPreM_CUR		  
#ifdef GLOBAL
	N_ZRTPreM_CUR(7)
#endif
;


