EXTERN CursorData_t	X_ZrtPos_CUR		  
#ifdef GLOBAL
	N_ZrtPos_CUR(0)
#endif
;

EXTERN CursorData_t	Y_ZrtPos_CUR		  
#ifdef GLOBAL
	N_ZrtPos_CUR(1)
#endif
;

EXTERN CursorData_t	Z_ZrtPos_CUR		  
#ifdef GLOBAL
	N_ZrtPos_CUR(2)
#endif
;

EXTERN CursorData_t	A_ZrtPos_CUR		  
#ifdef GLOBAL
	N_ZrtPos_CUR(3)
#endif
;

EXTERN CursorData_t	B_ZrtPos_CUR		  
#ifdef GLOBAL
	N_ZrtPos_CUR(4)
#endif
;

EXTERN CursorData_t	C_ZrtPos_CUR		  
#ifdef GLOBAL
	N_ZrtPos_CUR(5)
#endif
;

EXTERN CursorData_t	D_ZrtPos_CUR		  
#ifdef GLOBAL
	N_ZrtPos_CUR(6)
#endif
;

EXTERN CursorData_t	E_ZrtPos_CUR		  
#ifdef GLOBAL
	N_ZrtPos_CUR(7)
#endif
;
