EXTERN CursorData_t	X_ZrtCye_CUR		  
#ifdef GLOBAL
	N_ZrtCye_CUR(0)
#endif
;

EXTERN CursorData_t	Y_ZrtCye_CUR		  
#ifdef GLOBAL
	N_ZrtCye_CUR(1)
#endif
;

EXTERN CursorData_t	Z_ZrtCye_CUR		  
#ifdef GLOBAL
	N_ZrtCye_CUR(2)
#endif
;

EXTERN CursorData_t	A_ZrtCye_CUR		  
#ifdef GLOBAL
	N_ZrtCye_CUR(3)
#endif
;

EXTERN CursorData_t	B_ZrtCye_CUR		  
#ifdef GLOBAL
	N_ZrtCye_CUR(4)
#endif
;

EXTERN CursorData_t	C_ZrtCye_CUR		  
#ifdef GLOBAL
	N_ZrtCye_CUR(5)
#endif
;

EXTERN CursorData_t	D_ZrtCye_CUR		  
#ifdef GLOBAL
	N_ZrtCye_CUR(6)
#endif
;

EXTERN CursorData_t	E_ZrtCye_CUR		  
#ifdef GLOBAL
	N_ZrtCye_CUR(7)
#endif
;
