#include	"c_ncrt.h"

#define WIN_TITLE_FCOLOR		BRIGHTWHITE_USR
#define WIN_TITLE_BCOLOR		BLUE_USR

#define WIN_TEXT_FCOLOR 		BLACK_USR
#define WIN_TEXT_BCOLOR 		LIGHTGRAY_USR

#if 0
//#ifdef NEW_COLOR
#define TOUCH_TITLE_FCOLOR		BRIGHTWHITE_USR
#define TOUCH_TITLE_BCOLOR		BLUE_USR
#else
#define TOUCH_TITLE_FCOLOR		YELLOW_USR
#define TOUCH_TITLE_BCOLOR		GREEN_USR
#endif

#define MISS_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define MISS_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define QUAN_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define QUAN_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define SAFE_TITLE_FCOLOR		BRIGHTWHITE_USR
#define SAFE_TITLE_BCOLOR		LIGHTMAGENTA_USR

#define FILE_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define FILE_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define SPEED_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define SPEED_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define SPEED_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define SPEED_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define MODE_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define MODE_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define AXIS_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define AXIS_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define POS_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define POS_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define MAN_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define MAN_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define HAND_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define HAND_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define PARA_TITLE_FCOLOR		TOUCH_TITLE_FCOLOR
#define PARA_TITLE_BCOLOR		TOUCH_TITLE_BCOLOR

#define CCY_NAME_FCOLOR 		GRAY
#define CCY_NAME_BCOLOR 		LIGHTGRAY_USR

#define HELPBOX_MAIN_FCOLOR 	BLACK_USR
#define HELPBOX_MAIN_BCOLOR 	BRIGHTWHITE_USR

#define EDITBOX_MAIN_FCOLOR 	BLACK_USR
#define EDITBOX_MAIN_BCOLOR 	BRIGHTWHITE_USR

#define AIRBOX_MAIN_FCOLOR      BLACK_USR
#define AIRBOX_MAIN_BCOLOR      GRAY_14

#define CUR_PROG_FCOLOR 		YELLOW_USR
#define CUR_PROG_BCOLOR 		CYAN_USR


////////////////////////////////////////////////////////////////////////////////

#define MAIN_WIN_LX 			0
#define MAIN_WIN_LY 			0
#define MAIN_WIN_RX 			(SCRN_W-1)
#define MAIN_WIN_RY 			(SCRN_H-1-32)

#define TOOL_BAR_LX 			MAIN_WIN_LX
#define TOOL_BAR_LY 			(MAIN_WIN_RY+1)
#define TOOL_BAR_RX 			MAIN_WIN_RX
#define TOOL_BAR_RY 			(SCRN_H-1)

#define EDIT_BOX_LX 			(MAIN_WIN_LX+4-2)
#define EDIT_BOX_LX2      (EDIT_BOX_LX+4)
#define EDIT_BOX_LY 			(MAIN_WIN_LY+12*ASC_CHAR_H+4-2)
#define EDIT_BOX_RX 			(EDIT_BOX_LX+4 +ASC_CHAR_W*(SCRN_W/8-1) -1 )
#define EDIT_BOX_RY 			(EDIT_BOX_LY+4 +(ASC_CHAR_H+1)*(PAGE_LINES+1) -1)

#define AIR_BOX_OFF				((PAGE_CHARS-AIR_PAGE_CHARS)*ASC_CHAR_W-4) 
#define STATUS_BAR_LX			EDIT_BOX_LX
#define STATUS_BAR_LY			(EDIT_BOX_RY+2+2)

#define VSCROLL_LX				(EDIT_BOX_RX-2-ICON_W +3)
#define VSCROLL_LY				(EDIT_BOX_LY+2)
#define VSCROLL_RX				(EDIT_BOX_RX+0)
#define VSCROLL_RY				(EDIT_BOX_RY-2)

#define PARA_BOX_LX 			(MAIN_WIN_LX+4*ASC_CHAR_W)
#define PARA_BOX_LY 			(MAIN_WIN_LY+4*ASC_CHAR_H)
#define PARA_BOX_RX 			(MAIN_WIN_RX-4*ASC_CHAR_W)
//#define PARA_BOX_RY 			(PARA_BOX_LY+(ASC_CHAR_H+1)*24)
#define PARA_PAGE_LINE			((PARA_BOX_RY-PARA_BOX_LY+1)/(ASC_CHAR_H+1))
#define PARA_PAGE_CHARS 		((PARA_BOX_RX-PARA_BOX_LX+1)/ASC_CHAR_W)

#define HELP_BOX_LX 			(MAIN_WIN_LX+4-2)
#define HELP_BOX_LY 			(MAIN_WIN_LY+5*ASC_CHAR_H+4-2 +8)
//#define HELP_BOX_RX 			(HELP_BOX_LX+4 +ASC_CHAR_W*79 -1)
//#define HELP_BOX_RY 			(HELP_BOX_LY+4 +(ASC_CHAR_H+1)*21 -1)
#define HELP_PAGE_LINE			((HELP_BOX_RY-HELP_BOX_LY+1)/(ASC_CHAR_H+1))
#define HELP_PAGE_CHARS 		((HELP_BOX_RX-HELP_BOX_LX+1)/ASC_CHAR_W)

#define HELP_SCROLL_LX			(HELP_BOX_RX-2-ICON_W +1)
#define HELP_SCROLL_LY			(HELP_BOX_LY+2)
#define HELP_SCROLL_RX			(HELP_BOX_RX-2)
#define HELP_SCROLL_RY			(HELP_BOX_RY-2)

#define TOUCH_LX				(MAIN_WIN_LX+4-2)
#define TOUCH_LY				(MAIN_WIN_LY+2*ASC_CHAR_H-2 +4)
#define TOUCH_TITLE_CHARS		9
#define TOUCH_DATA_CHARS		7

#define MISS_LX 				(TOUCH_LX+TOUCH_TITLE_CHARS*ASC_CHAR_W+4 + TOUCH_DATA_CHARS*ASC_CHAR_W+4)
#define MISS_LY 				TOUCH_LY
#define MISS_TITLE_CHARS		(TOUCH_DATA_CHARS*2)
#define MISS_DATA_CHARS 		TOUCH_DATA_CHARS

#define QUAN_LX 				(MISS_LX+MISS_TITLE_CHARS*ASC_CHAR_W+4+4 + MISS_DATA_CHARS*ASC_CHAR_W+4)
#define QUAN_LY 				TOUCH_LY
#define QUAN_TITLE_CHARS		(TOUCH_DATA_CHARS*2)
#define QUAN_DATA_CHARS 		TOUCH_DATA_CHARS

#define SAFE_LX 				(QUAN_LX+QUAN_TITLE_CHARS*ASC_CHAR_W+4+4 + QUAN_DATA_CHARS*ASC_CHAR_W+4)
#define SAFE_LY 				TOUCH_LY
#define SAFE_TOTAL_CHARS		16

#define MODE_LX 				TOUCH_LX
#define MODE_LY 				(TOUCH_LY+2*ASC_CHAR_H+4+4)
#define MODE_TITLE_CHARS		TOUCH_TITLE_CHARS
#define MODE_DATA_CHARS 		TOUCH_DATA_CHARS

#define SPEED_LX				(MODE_LX+MODE_TITLE_CHARS*ASC_CHAR_W+4 + MODE_DATA_CHARS*ASC_CHAR_W+4)
#define SPEED_LY				MODE_LY
#define SPEED_TITLE_CHARS		(TOUCH_DATA_CHARS*2)
#define SPEED_DATA_CHARS		TOUCH_DATA_CHARS

#define FILE_LX 				(SPEED_LX+SPEED_TITLE_CHARS*ASC_CHAR_W+4+4 + SPEED_DATA_CHARS*ASC_CHAR_W+4)
#define FILE_LY 				MODE_LY
#if NEW_FILE
#define FILE_TITLE_CHARS		(TOUCH_TITLE_CHARS-1)
#define FILE_DATA_CHARS 		(TOUCH_DATA_CHARS*3-FILE_TITLE_CHARS)
#else
#define FILE_TITLE_CHARS		(TOUCH_DATA_CHARS*2)
#define FILE_DATA_CHARS			TOUCH_DATA_CHARS
#endif

#define FILE_COMMENT_LX 		(FILE_LX+FILE_TITLE_CHARS*ASC_CHAR_W+4+4 + FILE_DATA_CHARS*ASC_CHAR_W+4+8)
#define FILE_COMMENT_LY 		MODE_LY
#define FILE_COMMENT_CHARS		(16)



#define AXIS_LX 				(MAIN_WIN_LX+4-2)
#define AXIS_LY 				(MAIN_WIN_LY+6*ASC_CHAR_H-2 +8)
#define AXIS_TITLE_CHARS		TOUCH_TITLE_CHARS
#define AXIS_DATA_CHARS 		TOUCH_DATA_CHARS

#define POS_LX					AXIS_LX
#define POS_LY					(AXIS_LY+ASC_CHAR_H+4)
#define POS_TITLE_CHARS 		TOUCH_TITLE_CHARS
#define POS_DATA_CHARS			(TOUCH_DATA_CHARS+1)

#define MAN_LX					AXIS_LX
#define MAN_LY					(POS_LY+ASC_CHAR_H+4)
#define MAN_TITLE_CHARS 		TOUCH_TITLE_CHARS
#define MAN_DATA_CHARS			(TOUCH_DATA_CHARS+1)

#define HAND_LX 				AXIS_LX
#define HAND_LY 				(MAN_LY+ASC_CHAR_H+4)
#define HAND_TITLE_CHARS		TOUCH_TITLE_CHARS
#define HAND_DATA_CHARS 		(TOUCH_DATA_CHARS+1)

#define ROLL_LX 				(SCRN_W-82)
#define ROLL_LY 				(SAFE_LY+(ASC_CHAR_H+4)*3 + 4)

#define PARA_DATA_CHARS 		8

#define PASSWORD_LX 			((PARA_BOX_LX+PARA_BOX_RX-(PARA_DATA_CHARS*ASC_CHAR_W+4)*2)/2)
#define PASSWORD_LY 			(PARA_BOX_LY+1*(ASC_CHAR_H))

#define PARA_MOTOR_LX			(PARA_BOX_LX+2*ASC_CHAR_W)
#define PARA_MOTOR_LY			(PARA_BOX_LY+3*(ASC_CHAR_H)-5)

#define	PARA_LINE00_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*0)
#define	PARA_LINE01_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*1)
#define	PARA_LINE02_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*2)
#define	PARA_LINE03_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*3)
#define	PARA_LINE04_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*4)
#define	PARA_LINE05_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*5)
#define	PARA_LINE06_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*6)
#define	PARA_LINE07_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*7)
#define	PARA_LINE08_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*8)
#define PARA_LINE09_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*9)
#define PARA_LINE10_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*10)
#define PARA_LINE11_LY 		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*11)
#define PARA_LINE12_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*12)
#define PARA_LINE13_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*13)
#define PARA_LINE14_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*14)
#define PARA_LINE15_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*15)
#define PARA_LINE16_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*16)
#define PARA_LINE17_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*17)
#define PARA_LINE18_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*18)
#define PARA_LINE19_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*19)
#define PARA_LINE20_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*20)
#define PARA_LINE21_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*21)
#define PARA_LINE22_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*22)
#define PARA_LINE23_LY		(PARA_MOTOR_LY+(ASC_CHAR_H+4)*23)

#define PARA_Y0_LY				PARA_LINE11_LY
#define PARA_NEAR_LY			PARA_LINE12_LY
#define PARA_SPIN_ZRT_LY	PARA_LINE13_LY
#define PARA_WILE_MODE_LY	PARA_LINE14_LY
#define PARA_PRODPASS_LY	PARA_LINE15_LY
#define PARA_OilChk_LY	PARA_LINE16_LY

#define PARA_SUM_LX 			PARA_MOTOR_LX
#define PARA_SUM_LY 			(PARA_LINE12_LY+1*(ASC_CHAR_H+4))



#define PARA_EXT11_LX			PARA_MOTOR_LX	                
#define PARA_EXT11_LY			(GRID_YS+(ASC_CHAR_H+4)*4)

#define PARA_SPDLinkMode_LX		PARA_MOTOR_LX	                
#define PARA_SPDLinkMode_LY		(GRID_YS+(ASC_CHAR_H+4)*5)

#define PARA_EXT12_LX			PARA_MOTOR_LX	
#define PARA_EXT12_LY			(GRID_YS+(ASC_CHAR_H+4)*4)

#define PARA_EXT13_LX			PARA_MOTOR_LX	
#define PARA_EXT13_LY			(GRID_YS+(ASC_CHAR_H+4)*5)


#define Y0_LX				331+4
#define Y0_LY				240-15

#define JMPNN_LX            331+31
#define JMPNN_LY            240-8

#define PROG_BUF_LINES			MAX_PROG_LINE

